{{- if and .Values.cloudabilityMcp.enabled .Values.cloudabilityMcp.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-platform-engineering.cloudabilityMcp.secretName" . }}
  labels:
    {{- include "ai-platform-engineering.cloudabilityMcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.cloudabilityMcp.secret.data | nindent 2 }}
{{- end }}
