{{- if and .Values.litellmMcp.enabled .Values.litellmMcp.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-platform-engineering.litellmMcp.secretName" . }}
  labels:
    {{- include "ai-platform-engineering.litellmMcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.litellmMcp.secret.data | nindent 2 }}
{{- end }}
