apiVersion: v1
kind: ConfigMap
metadata:
  name: task-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ai-platform-engineering.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  task_config.yaml: |
{{- if .Values.taskConfig }}
{{ .Values.taskConfig | nindent 4 }}
{{- else }}
{{ .Files.Get "data/task_config.yaml" | nindent 4 }}
{{- end }}
