export const SPEAKERS_COLLECTIVE_APP_ID = "speakers-collective";

export const SPEAKERS_COLLECTIVE_MANIFEST = {
  id: SPEAKERS_COLLECTIVE_APP_ID,
  displayName: "Speakers Collective",
  description:
    "A self-contained, source-backed dashboard with governed agent proposals for speaking opportunities.",
  apiVersion: "1.0",
  runtime: {
    kind: "proxied-next-zone",
    mountPath: "/apps/speakers-collective",
    chrome: "iframe",
  },
  ui: {
    contractVersion: "1.0",
    surface: "hosted",
    routes: ["/", "/example"],
    preferences: {
      schemaVersion: "1.0",
      fields: [
        {
          key: "density",
          label: "Dashboard density",
          type: "enum",
          default: "compact",
          options: [
            { label: "Compact", value: "compact" },
            { label: "Comfortable", value: "comfortable" },
          ],
        },
        {
          key: "textScale",
          label: "Text size",
          type: "enum",
          default: "default",
          options: [
            { label: "Small", value: "small" },
            { label: "Default", value: "default" },
            { label: "Large", value: "large" },
            { label: "Extra large", value: "xl" },
          ],
        },
        {
          key: "defaultView",
          label: "Default event view",
          type: "enum",
          default: "open",
          options: [
            { label: "Open CFPs", value: "open" },
            { label: "Closing soon", value: "soon" },
            { label: "Watching", value: "watching" },
            { label: "All opportunities", value: "all" },
          ],
        },
      ],
    },
  },
  authorization: { resourceType: "agentic_app", launchAction: "use" },
  surfaces: {
    showInHub: true,
    showInTopNav: false,
    navOrder: 50,
    homeEligible: false,
    overlays: ["chat"],
  },
  access: {
    requiredRoles: ["user"],
    tokenScopes: [
      "speakers-collective:read",
      "speakers-collective:propose",
      "speakers-collective:refresh",
      "speakers-collective:approve",
      "speakers-collective:publish",
    ],
    canUseCustomAgents: true,
    policyActions: [
      {
        action: "proxy:GET",
        description: "Read the Speakers Collective dashboard and event source",
        defaultEffect: "allow",
        requiredScopes: ["speakers-collective:read"],
        casAction: "use",
      },
      {
        action: "proxy:HEAD",
        description: "Probe the Speakers Collective runtime",
        defaultEffect: "allow",
        requiredScopes: ["speakers-collective:read"],
        casAction: "use",
      },
      {
        action: "proposal:create",
        description: "Create a governed event proposal",
        method: "POST",
        path: "/api/proposals",
        defaultEffect: "allow",
        requiredScopes: ["speakers-collective:propose"],
        casAction: "write",
      },
      {
        action: "refresh:start",
        description: "Start an authorized opportunity discovery refresh",
        method: "POST",
        path: "/api/refresh",
        defaultEffect: "allow",
        requiredScopes: ["speakers-collective:refresh"],
        casAction: "write",
      },
      {
        action: "proposal:review",
        description: "Approve or reject a governed event proposal",
        method: "POST",
        path: "/api/proposals/:proposalId/review",
        defaultEffect: "allow",
        requiredScopes: ["speakers-collective:approve"],
        casAction: "approve",
      },
      {
        action: "publication:create",
        description: "Publish approved proposals to the opportunity radar",
        method: "POST",
        path: "/api/publications",
        defaultEffect: "allow",
        requiredScopes: ["speakers-collective:publish"],
        casAction: "manage",
      },
      {
        action: "version:rollback",
        description: "Roll back to an immutable published version",
        method: "POST",
        path: "/api/versions/:versionId/rollback",
        defaultEffect: "allow",
        requiredScopes: ["speakers-collective:publish"],
        casAction: "manage",
      },
    ],
  },
  assistant: {
    enabled: true,
    agentId: "agent-speakers-collective",
    schemaVersions: ["1.0"],
    maxContextBytes: 12288,
    capability: "contextual-chat",
    suggestions: true,
    label: "Ask Speakers",
    agentName: "Speakers Collective Agent",
  },
  agents: [
    {
      id: "speakers-collective-agent",
      displayName: "Speakers Collective Agent",
      required: true,
      dynamicAgentId: "agent-speakers-collective",
      capabilities: ["opportunity-search", "cfp-tracking", "governed-crud"],
    },
  ],
  data: {
    apiBasePath: "/api/speakers-collective",
    eventChannels: ["speakers-collective.events.updated"],
  },
  health: {
    endpoint: "/health/ready",
    timeoutMs: 1500,
    blockLaunchWhen: ["degraded", "unreachable"],
  },
  catalog: {
    categories: ["community", "events", "speaking"],
    capabilities: [
      "cfp-discovery",
      "deadline-tracking",
      "team-filtering",
      "assistant-context-bridge",
      "mcp-proposals",
      "immutable-publications",
    ],
  },
};
