[project]
name = "clients"
version = "0.1.0"
description = "Clients for nexigraph"
readme = "README.md"
authors = [
    { email = "subbaksh@cisco.com" }
]
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.38",
    "core",
    "kubernetes>=33.1.0",
    "python-dotenv>=1.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
core = { path = "../core" }
