# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api-reporting/v2/incidents operations"""

import logging
from typing import Dict, Any, Optional
from ..api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def get_api_reporting_v2_incidents(
    offset: Optional[int] = None,
    limit: Optional[int] = None,
    entityId: Optional[str] = None,
    incidentNumber: Optional[str] = None,
    startedAfter: Optional[str] = None,
    startedBefore: Optional[str] = None,
    host: Optional[str] = None,
    service: Optional[str] = None,
    currentPhase: Optional[str] = None,
    routingKey: Optional[str] = None,
) -> Dict[str, Any]:
    """
        Get/search incident history

        OpenAPI Description:
            Retrieve incident history for your company, searching over date ranges and with filtering options.

    This API may be called a maximum of once a minute.

    Incident requests are paginated with a offset and limit query string parameters.
      The query for incidents is run and offset records are skipped, after which limit records will be returned.

    The default offset is 0 and the default limit is 20. The maximum value allowed for limit is 100.

    Unless specified otherwise with the parameter currentPhase, the response will only contain resolved incidents.

    On return, the total number of records available for that query will be returned in the payload as 'total'.


        Args:

            offset (int): The offset within the set of matching incidents

            limit (int): The maximum number of matching incidents to return (100 max)

            entityId (str): The entity ID involved  This is the unique identifier for the entity causing the incident.

            incidentNumber (str): The incident number as shown in VictorOps Multiple values and ranges are allowed: 4,5,20:50


            startedAfter (str): Return incidents started after this timestamp Specify the timestamp in ISO8601 format

            startedBefore (str): Find incidents started before this timestamp  Specify the timestamp in ISO8601 format

            host (str): The host involved in the incident Multiple values can be separated with commas.

            service (str): The service involved in the incident (if any) Multiple values can be separated with commas.

            currentPhase (str): The current phase of the incident "resolved", "triggered" or "acknowledged". Multiple values can be separated with commas. By default, response contains only "resolved" incidents

            routingKey (str): The original routing of the incident


        Returns:
            Dict[str, Any]: The JSON response from the API call.

        Raises:
            Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /api-reporting/v2/incidents")

    params = {}
    data = {}

    if offset is not None:
        params["offset"] = str(offset).lower() if isinstance(offset, bool) else offset

    if limit is not None:
        params["limit"] = str(limit).lower() if isinstance(limit, bool) else limit

    if entityId is not None:
        params["entityId"] = str(entityId).lower() if isinstance(entityId, bool) else entityId

    if incidentNumber is not None:
        params["incidentNumber"] = (
            str(incidentNumber).lower() if isinstance(incidentNumber, bool) else incidentNumber
        )

    if startedAfter is not None:
        params["startedAfter"] = (
            str(startedAfter).lower() if isinstance(startedAfter, bool) else startedAfter
        )

    if startedBefore is not None:
        params["startedBefore"] = (
            str(startedBefore).lower() if isinstance(startedBefore, bool) else startedBefore
        )

    if host is not None:
        params["host"] = str(host).lower() if isinstance(host, bool) else host

    if service is not None:
        params["service"] = str(service).lower() if isinstance(service, bool) else service

    if currentPhase is not None:
        params["currentPhase"] = (
            str(currentPhase).lower() if isinstance(currentPhase, bool) else currentPhase
        )

    if routingKey is not None:
        params["routingKey"] = str(routingKey).lower() if isinstance(routingKey, bool) else routingKey

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request("/api-reporting/v2/incidents", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
