# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api-public/v1/incidents operations.

Only the create (POST) endpoint is exposed. The GET endpoint is replaced
by /api-reporting/v2/incidents which supports server-side filtering and
multi-org fan-out.
"""

import json
import logging
from typing import Any, Dict, Optional

from ..api.client import assemble_nested_body, make_api_request
from ..models.incident import IncidentCreate

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def post_api_public_v1_incidents(
    incident: IncidentCreate,
    org_slug: Optional[str] = None,
) -> str:
    """Create a new incident.

    OpenAPI Description:
        Create a new incident.

    This API may be called a maximum of 2 times per second.
    """
    logger.debug("Making POST request to /api-public/v1/incidents")

    flat_body: Dict[str, Any] = {}
    if incident is not None:
        flat_body = incident.model_dump()
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        "/api-public/v1/incidents", method="POST",
        org_slug=org_slug, params={}, data=data,
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return json.dumps({"error": response.get("error", "Request failed")}, indent=2)
    return json.dumps(response, indent=2, default=str)
