{{- if and (not .Values.externalSecrets.enabled) (not .Values.secrets.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-secret
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.argocdToken }}
  ARGOCD_TOKEN: {{ .Values.secrets.argocdToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.argocdApiUrl }}
  ARGOCD_API_URL: {{ .Values.secrets.argocdApiUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.argocdVerifySsl }}
  ARGOCD_VERIFY_SSL: {{ .Values.secrets.argocdVerifySsl | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.additionalSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
