[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pagerduty_mcp"
version = "0.1.0"
description = "PagerDuty MCP Server"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Cisco CNOE", email = "cnoe@cisco.com"},
]
license = {text = "Apache-2.0"}
dependencies = [
    "fastmcp>=0.3.1",
    "python-dotenv>=1.0.0",
    "pydantic>=2.0.0,<3.0.0",
    "httpx>=0.24.1",
    "jinja2>=3.1.2"
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "mypy",
    "pytest",
    "ruff",
]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.9"
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
warn_no_return = true 