 services:
  neo4j:
    image: neo4j:latest
    volumes:
        - ./.neo4j/logs:/logs
        - ./.neo4j/config:/config
        - ./.neo4j/data:/data
        - ./.neo4j/plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/dummy_password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true

  neo4j-ontology:
    image: neo4j:latest
    volumes:
        - ./.neo4j-ontology/logs:/logs
        - ./.neo4j-ontology/config:/config
        - ./.neo4j-ontology/data:/data
        - ./.neo4j-ontology/plugins:/plugins
    ports:
      - "7688:7687"
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/dummy_password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true

  nexigraph_redis:
    image: redis
    command:
      - /bin/sh
      - -c
      - redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  nexigraph_server:
    ports:
      - "8095:8095"
    environment:
        LOG_LEVEL: DEBUG
        REDIS_HOST: nexigraph_redis
        NEO4J_ADDR: neo4j://neo4j:7687
        NEO4J_ONTOLOGY_ADDR: neo4j://neo4j-ontology:7687
        NEO4J_USERNAME: neo4j
        NEO4J_PASSWORD: dummy_password
        API_KEYS: dummy_key
        CLEANUP_INTERVAL: 86400
    restart: unless-stopped
    depends_on:
      - neo4j
      - nexigraph_redis
    build:
      context: ./nexigraph/
      dockerfile: ./server/Dockerfile
  
  # agent_graph_gen:
  #   environment:
  #       LOG_LEVEL: DEBUG
  #       REDIS_HOST: nexigraph_redis
  #       NEO4J_ADDR: neo4j://neo4j:7687
  #       NEO4J_ONTOLOGY_ADDR: neo4j://neo4j-ontology:7687
  #       NEO4J_USERNAME: neo4j
  #       NEO4J_PASSWORD: dummy_password
  #       SYNC_INTERVAL: 86400
  #   env_file:
  #     - ../../../../.env
  #   restart: unless-stopped
  #   depends_on:
  #     - nexigraph_server
  #     - neo4j
  #     - nexigraph_redis
  #   build:
  #     context: ./nexigraph/
  #     dockerfile: ./agent_graph_gen/Dockerfile
  agent_graph_qa:
    ports:
      - "8096:8096"
    environment:
        LOG_LEVEL: DEBUG
        REDIS_HOST: nexigraph_redis
        NEO4J_ADDR: neo4j://neo4j:7687
        NEO4J_USERNAME: neo4j
        NEO4J_PASSWORD: dummy_password
    env_file:
      - ../../../../.env
    restart: unless-stopped
    depends_on:
      - neo4j
    build:
      context: ./nexigraph/
      dockerfile: ./agent_graph_qa/Dockerfile
  
  nexigraph_dummy_client:
    depends_on:
      - nexigraph_server
    environment:
       SERVER_ADDR: http://nexigraph_server:8095
       API_KEY: dummy_key
       DUMMY_ENTITIES_FILE: dummy_data.json
    restart: unless-stopped
    volumes:
      - ./example/dummy_data.json:/app/clients/dummy_data.json
    build:
      context: ./nexigraph/
      dockerfile: ./clients/Dockerfile