apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform-engineering-git
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Option 2: Use Git repository source
    repoURL: https://github.com/cnoe-io/ai-platform-engineering.git
    path: helm
    targetRevision: HEAD  # or specify a specific branch/tag
    helm:
      # Add your values here
      values: |
        # Enable the agents you want to deploy
        agent-argocd:
          enabled: true
          nameOverride: "agent-argocd"
          image:
            repository: "ghcr.io/cnoe-io/agent-argocd"
        
        agent-github:
          enabled: true
          nameOverride: "agent-github"
          image:
            repository: "ghcr.io/cnoe-io/agent-github"
        
        # Configure for EKS with ALB
        ingress:
          enabled: true
          className: "alb"
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
          hosts:
            - host: ai-platform.your-domain.com  # Replace with your domain
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform-engineering
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
