services:
  # AI Platform Engineer Multi-Agent System
  # ai-platform-engineer:
  #   image: docker.io/library/ai-platform-engineering:latest
  #   # image: ghcr.io/cnoe-io/ai-platform-engineering:stable
  #   container_name: platform-engineer
  #   depends_on:
  #     - agent-argocd
  #     - agent-atlassian
  #     - agent-pagerduty
  #     - agent-github
  #     - agent-slack
  #   env_file:
  #     - .env
  #   ports:
  #     # Expose the AI Platform Engineer agent on port 8000
  #     - "8000:8000"
  #   environment:
  #     - AGENT_PROTOCOL=fastapi
  #     - ARGOCD_AGENT_HOST=agent-argocd
  #     - ARGOCD_AGENT_PORT=8000
  #     - ATLASSIAN_AGENT_HOST=agent-atlassian
  #     - ATLASSIAN_AGENT_PORT=8000
  #     - GITHUB_AGENT_HOST=agent-github
  #     - GITHUB_AGENT_PORT=8000
  #     - PAGERDUTY_AGENT_HOST=agent-pagerduty
  #     - PAGERDUTY_AGENT_PORT=8000
  #     - SLACK_AGENT_HOST=agent-slack
  #     - SLACK_AGENT_PORT=8000

  #   volumes:
  #     - .env:/app/.env
  #   command: platform-engineer
  # # Agent ArgoCD
  agent-argocd:
    image: ghcr.io/cnoe-io/agent-argocd:a2a-stable
    container_name: agent-argocd
    volumes:
      - ./.env:/app/.env
    ports:
      # Expose the ArgoCD agent on port 8080
      - "8001:8000"
  # Agent Atlassian
  agent-atlassian:
    image: ghcr.io/cnoe-io/agent-atlassian:a2a-stable
    container_name: agent-atlassian
    volumes:
      - ./.env:/app/.env
    ports:
      # Expose the Atlassian agent on port 8002
      - "8002:8000"
  # Agent GitHub
  agent-github:
    image: ghcr.io/cnoe-io/agent-github:a2a-stable
    container_name: agent-github
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/app/.env
    ports:
      # Expose the GitHub agent on port 8003
      - "8003:8000"
  # Agent PagerDuty
  agent-pagerduty:
    image: ghcr.io/cnoe-io/agent-pagerduty:a2a-stable
    container_name: agent-pagerduty
    volumes:
      - ./.env:/app/.env
    ports:
      # Expose the PagerDuty agent on port 8004
      - "8004:8000"
  # Agent Slack
  agent-slack:
    image: ghcr.io/cnoe-io/agent-slack:a2a-stable
    container_name: agent-slack
    volumes:
      - ./.env:/app/.env
    ports:
      # Expose the Slack agent on port 8005
      - "8005:8000"
  # Sample UI container to interact with A2A applications
  ui:
    image: ghcr.io/eti-demos/agentconnect
    container_name: ui
    ports:
      - "3001:3001"
  # backstage-agent-forge:
  #   image: ghcr.io/cnoe-io/backstage-agent-forge:stable
  #   container_name: backstage-agent-forge
  #   ports:
  #     - "3000:3000"