{{- if not .Values.secrets.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-argocd.fullname" . }}-secret
  labels:
    {{- include "agent-argocd.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.llmProvider }}
  LLM_PROVIDER: {{ .Values.secrets.llmProvider | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureOpenaiApiKey }}
  AZURE_OPENAI_API_KEY: {{ .Values.secrets.azureOpenaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureOpenaiEndpoint }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.secrets.azureOpenaiEndpoint | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureOpenaiApiVersion }}
  AZURE_OPENAI_API_VERSION: {{ .Values.secrets.azureOpenaiApiVersion | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureOpenaiDeployment }}
  AZURE_OPENAI_DEPLOYMENT: {{ .Values.secrets.azureOpenaiDeployment | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicModelName }}
  ANTHROPIC_MODEL_NAME: {{ .Values.secrets.anthropicModelName | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiEndpoint }}
  OPENAI_ENDPOINT: {{ .Values.secrets.openaiEndpoint | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiModelName }}
  OPENAI_MODEL_NAME: {{ .Values.secrets.openaiModelName | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.awsProfile }}
  AWS_PROFILE: {{ .Values.secrets.awsProfile | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.awsRegion }}
  AWS_REGION: {{ .Values.secrets.awsRegion | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.awsBedrockModelId }}
  AWS_BEDROCK_MODEL_ID: {{ .Values.secrets.awsBedrockModelId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.awsBedrockProvider }}
  AWS_BEDROCK_PROVIDER: {{ .Values.secrets.awsBedrockProvider | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.googleApiKey }}
  GOOGLE_API_KEY: {{ .Values.secrets.googleApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.googleApplicationCredentials }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.secrets.googleApplicationCredentials | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.vertexaiModelName }}
  VERTEXAI_MODEL_NAME: {{ .Values.secrets.vertexaiModelName | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.argocdToken }}
  ARGOCD_TOKEN: {{ .Values.secrets.argocdToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.argocdApiUrl }}
  ARGOCD_API_URL: {{ .Values.secrets.argocdApiUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.argocdVerifySsl }}
  ARGOCD_VERIFY_SSL: {{ .Values.secrets.argocdVerifySsl | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.additionalSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
