# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

#!/usr/bin/env python3
"""
 MCP Server

This server provides a Model Context Protocol (MCP) interface to the ,
allowing large language models and AI assistants to interact with the service.
"""

import logging
import os
from dotenv import load_dotenv
from fastmcp import FastMCP

from mcp_victorops.tools import (
    api_public_v2_user,
    api_reporting_v2_incidents,
    api_public_v1_incidents,
    incidentnumber_notes_notename,
    incidentnumber_notes,
    api_public_v1_chat,
    api_public_v1_team,
    api_public_v2_team_oncall,
    orgs,
)

def main():
    # Load environment variables
    load_dotenv()

    # Configure logging
    logging.basicConfig(level=logging.DEBUG)

    # Suppress noisy debug logs
    logging.getLogger("sse_starlette.sse").setLevel(logging.INFO)
    logging.getLogger("mcp.server.lowlevel.server").setLevel(logging.INFO)

    # Get MCP configuration from environment variables
    MCP_MODE = os.getenv("MCP_MODE", "STDIO")

    # Get host and port for server
    MCP_HOST = os.getenv("MCP_HOST", "localhost")
    MCP_PORT = int(os.getenv("MCP_PORT", "8000"))

    logging.info("Starting MCP server in {} mode on {}:{}".format(MCP_MODE, MCP_HOST, MCP_PORT))

    # Get server name from environment variables
    SERVER_NAME = os.getenv("SERVER_NAME", "VictorOps")
    logging.info('*' * 40)
    logging.info("MCP Server name: {}".format(SERVER_NAME))
    logging.info('*' * 40)

    # Create server instance
    mcp = FastMCP(f"{SERVER_NAME} MCP Server")

    # Register tools
    mcp.tool()(orgs.list_victorops_orgs)
    mcp.tool()(api_public_v1_incidents.get_api_public_v1_incidents)
    mcp.tool()(api_public_v2_user.get_api_public_v2_user)
    mcp.tool()(api_reporting_v2_incidents.get_api_reporting_v2_incidents)
    mcp.tool()(api_public_v1_incidents.post_api_public_v1_incidents)
    mcp.tool()(incidentnumber_notes.get_api_public_v1_incidents_incident_number_notes)
    mcp.tool()(incidentnumber_notes.post_api_public_v1_incidents_incident_number_notes)
    mcp.tool()(incidentnumber_notes_notename.put_api_public_v1_incidents_incident_number_notes_note_name)
    mcp.tool()(incidentnumber_notes_notename.delete_api_public_v1_incidents_incident_number_notes_note_name)
    mcp.tool()(api_public_v1_chat.post_api_public_v1_chat)
    mcp.tool()(api_public_v1_team.get_api_public_v1_team)
    mcp.tool()(api_public_v2_team_oncall.get_api_public_v2_team_oncall_schedule)

    # Run the MCP server
    if MCP_MODE.lower() in ["sse", "http"]:
        mcp.run(transport=MCP_MODE.lower(), host=MCP_HOST, port=MCP_PORT)
    else:
        mcp.run(transport=MCP_MODE.lower())


if __name__ == "__main__":
    main()
