{{- if hasKey .Values "global" }}
{{- if hasKey .Values.global "externalSecrets" }}
{{- if and (not .Values.global.externalSecrets.enabled) (not .Values.global.secrets.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: llm-secret
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.secrets.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
