{{- if .Values.global.createLlmSecret }}
{{- if eq (include "ai-platform-engineering.externalSecrets.enabled" .) "false" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.llmSecrets.secretName }}
  labels:
    {{- include "ai-platform-engineering.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.llmSecrets.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}