{{- if and (include "ai-platform-engineering.createTraditionalSecrets" . | eq "true") (include "ai-platform-engineering.useCustomSecretName" . | eq "false") }}
apiVersion: v1
kind: Secret
metadata:
  name: llm-secret
  labels:
    {{- include "ai-platform-engineering.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (hasKey .Values "global") (hasKey .Values.global "secrets") (hasKey .Values.global.secrets "data") }}
  {{- range $key, $value := .Values.global.secrets.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
