{{- if and (not .Values.externalSecrets.enabled) (not .Values.global.secrets.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-llm-secret
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  LLM_PROVIDER: {{ .Values.global.secrets.llmProvider | b64enc | quote }}

  # --- Use Azure OpenAI ---
  {{- if .Values.global.secrets.azureOpenaiApiKey }}
  AZURE_OPENAI_API_KEY: {{ .Values.global.secrets.azureOpenaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.secrets.azureOpenaiEndpoint }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.global.secrets.azureOpenaiEndpoint | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.secrets.azureOpenaiApiVersion }}
  AZURE_OPENAI_API_VERSION: {{ .Values.global.secrets.azureOpenaiApiVersion | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.secrets.azureOpenaiDeployment }}
  AZURE_OPENAI_DEPLOYMENT: {{ .Values.global.secrets.azureOpenaiDeployment | b64enc | quote }}
  {{- end }}

  # --- Or Use OpenAI ---
  {{- if .Values.global.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.global.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.secrets.openaiEndpoint }}
  OPENAI_ENDPOINT: {{ .Values.global.secrets.openaiEndpoint | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.secrets.openaiModelName }}
  OPENAI_MODEL_NAME: {{ .Values.global.secrets.openaiModelName | b64enc | quote }}
  {{- end }}

  # --- Or Use AWS Bedrock ---
  {{- if .Values.global.secrets.awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.secrets.awsAccessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.secrets.awsSecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.secrets.awsSecretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.secrets.awsRegion }}
  AWS_REGION: {{ .Values.global.secrets.awsRegion | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.secrets.awsBedrockModelId }}
  AWS_BEDROCK_MODEL_ID: {{ .Values.global.secrets.awsBedrockModelId | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.secrets.awsBedrockProvider }}
  AWS_BEDROCK_PROVIDER: {{ .Values.global.secrets.awsBedrockProvider | b64enc | quote }}
  {{- end }}
{{- end }}
