apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-supervisor-agent-env" .Release.Name }}
data:
  {{- $port := (index .Values "supervisor-agent" "multiAgentConfig" "port" | default "8000") -}}
  {{- range $name, $enabled := (default dict .Values.global.enabledSubAgents) }}
  {{- if $enabled }}
  {{- $ENV := upper $name }}
  {{ $ENV }}_AGENT_HOST: {{ printf "%s-agent-%s" $.Release.Name $name | quote }}
  {{ $ENV }}_AGENT_PORT: {{ printf "%v" $port | quote }}
  ENABLE_{{ $ENV }}: "true"
  {{- end }}
  {{- end }}
