# Copyright 2025 CNOE Contributors
# SPDX-License-Identifier: Apache-2.0
"""
Human-in-the-Loop (HITL) Handler

Handles caipe_form artifacts with interactive Slack Block Kit elements:
- Dropdown menus -> Slack static_select
- Text fields -> Slack plain_text_input
- Approve/Reject buttons -> Slack button elements
- Form submission callbacks via Slack interactivity
"""

import json
import os
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field

APP_NAME = os.environ.get("SLACK_INTEGRATION_APP_NAME", os.environ.get("APP_NAME", "CAIPE"))
from loguru import logger


@dataclass
class FormField:
    """Represents a form field"""

    field_id: str
    field_type: str  # text, select, multiselect
    label: str
    placeholder: Optional[str] = None
    options: Optional[List[Dict[str, str]]] = None
    required: bool = False
    default_value: Optional[str] = None


@dataclass
class FormAction:
    """Represents a form action button"""

    action_id: str
    label: str
    style: str = "primary"
    value: Optional[str] = None


@dataclass
class HITLForm:
    """Represents a complete HITL form"""

    form_id: str
    title: str
    description: str = ""
    fields: List[FormField] = field(default_factory=list)
    actions: List[FormAction] = field(default_factory=list)
    task_id: Optional[str] = None
    context_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


def parse_form_data(
    form_data: Dict[str, Any], task_id: str = None, context_id: str = None
) -> HITLForm:
    """Parse form data from caipe_form artifact into HITLForm."""
    form = HITLForm(
        form_id=form_data.get("form_id", f"hitl_form_{task_id or 'unknown'}"),
        title=form_data.get("title", "Action Required"),
        description=form_data.get("description", ""),
        task_id=task_id,
        context_id=context_id,
        metadata=form_data.get("metadata", {}),
    )

    for field_data in form_data.get("fields", []):
        form_field = FormField(
            field_id=field_data.get("id", field_data.get("name", "")),
            field_type=field_data.get("type", "text"),
            label=field_data.get("label", field_data.get("name", "")),
            placeholder=field_data.get("placeholder"),
            options=field_data.get("options"),
            required=field_data.get("required", False),
            default_value=field_data.get("default"),
        )
        form.fields.append(form_field)

    for action_data in form_data.get("actions", []):
        action = FormAction(
            action_id=action_data.get("id", action_data.get("name", "")),
            label=action_data.get("label", action_data.get("name", "")),
            style=action_data.get("style", "primary"),
            value=action_data.get("value"),
        )
        form.actions.append(action)

    if not form.actions:
        form.actions = [
            FormAction(action_id="approve", label="Approve", style="primary"),
            FormAction(action_id="reject", label="Reject", style="danger"),
        ]

    return form


def format_hitl_form_blocks(form: HITLForm) -> List[Dict[str, Any]]:
    """Format a HITLForm as Slack Block Kit blocks."""
    blocks = []

    blocks.append(
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"{form.title}", "emoji": True},
        }
    )

    if form.description:
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": form.description},
            }
        )

    blocks.append({"type": "divider"})

    for form_field in form.fields:
        field_block = _format_form_field(form_field, form.form_id)
        if field_block:
            blocks.append(field_block)

    if form.actions:
        action_elements = []
        for action in form.actions:
            button = {
                "type": "button",
                "text": {"type": "plain_text", "text": action.label, "emoji": True},
                "action_id": f"{form.form_id}_{action.action_id}",
                "value": json.dumps(
                    {
                        "action": action.action_id,
                        "form_id": form.form_id,
                        "task_id": form.task_id,
                        "context_id": form.context_id,
                    }
                ),
            }

            if action.style == "primary":
                button["style"] = "primary"
            elif action.style == "danger":
                button["style"] = "danger"

            action_elements.append(button)

        blocks.append({"type": "divider"})
        blocks.append({"type": "actions", "elements": action_elements})

    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"_Please respond to continue • This form was generated by {APP_NAME}_",
                }
            ],
        }
    )

    return blocks


def _format_form_field(form_field: FormField, form_id: str) -> Optional[Dict[str, Any]]:
    """Format a single form field as a Slack block."""
    action_id = f"{form_id}_{form_field.field_id}"

    if form_field.field_type == "select":
        options = []
        for opt in form_field.options or []:
            options.append(
                {
                    "text": {"type": "plain_text", "text": opt.get("label", opt.get("value", ""))},
                    "value": opt.get("value", opt.get("label", "")),
                }
            )

        if not options:
            return None

        element = {
            "type": "static_select",
            "action_id": action_id,
            "placeholder": {
                "type": "plain_text",
                "text": form_field.placeholder or f"Select {form_field.label}",
            },
            "options": options,
        }

        if form_field.default_value:
            for opt in options:
                if opt["value"] == form_field.default_value:
                    element["initial_option"] = opt
                    break

        return {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*{form_field.label}*" + (" _(required)_" if form_field.required else ""),
            },
            "accessory": element,
        }

    elif form_field.field_type == "multiselect":
        options = []
        for opt in form_field.options or []:
            options.append(
                {
                    "text": {"type": "plain_text", "text": opt.get("label", opt.get("value", ""))},
                    "value": opt.get("value", opt.get("label", "")),
                }
            )

        if not options:
            return None

        return {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*{form_field.label}*" + (" _(required)_" if form_field.required else ""),
            },
            "accessory": {
                "type": "multi_static_select",
                "action_id": action_id,
                "placeholder": {
                    "type": "plain_text",
                    "text": form_field.placeholder or f"Select {form_field.label}",
                },
                "options": options,
            },
        }

    elif form_field.field_type == "text":
        return {
            "type": "input",
            "block_id": f"block_{action_id}",
            "element": {
                "type": "plain_text_input",
                "action_id": action_id,
                "placeholder": {
                    "type": "plain_text",
                    "text": form_field.placeholder or f"Enter {form_field.label}",
                },
            },
            "label": {"type": "plain_text", "text": form_field.label},
            "optional": not form_field.required,
        }

    elif form_field.field_type == "textarea":
        return {
            "type": "input",
            "block_id": f"block_{action_id}",
            "element": {
                "type": "plain_text_input",
                "action_id": action_id,
                "multiline": True,
                "placeholder": {
                    "type": "plain_text",
                    "text": form_field.placeholder or f"Enter {form_field.label}",
                },
            },
            "label": {"type": "plain_text", "text": form_field.label},
            "optional": not form_field.required,
        }

    return None


def extract_form_response(payload: Dict[str, Any], form_id: str) -> Dict[str, Any]:
    """Extract form field values from a Slack interaction payload."""
    response = {}

    state = payload.get("state", {})
    values = state.get("values", {})

    for block_id, block_values in values.items():
        for action_id, action_value in block_values.items():
            if action_id.startswith(f"{form_id}_"):
                field_id = action_id[len(f"{form_id}_"):]

                if "value" in action_value:
                    response[field_id] = action_value["value"]
                elif "selected_option" in action_value:
                    response[field_id] = action_value["selected_option"]["value"]
                elif "selected_options" in action_value:
                    response[field_id] = [opt["value"] for opt in action_value["selected_options"]]

    return response


def format_form_submission_response(
    action: str,
    form_values: Dict[str, Any],
    success: bool = True,
) -> List[Dict[str, Any]]:
    """Format a response message after form submission."""
    if success:
        icon = "✅"
        status = "submitted successfully"
    else:
        icon = "❌"
        status = "submission failed"

    blocks = [
        {"type": "section", "text": {"type": "mrkdwn", "text": f"{icon} Form {status}"}},
        {
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": f"_Action: {action.title()}_"}],
        },
    ]

    if form_values:
        value_lines = []
        for field_id, value in form_values.items():
            if isinstance(value, list):
                value_str = ", ".join(value)
            else:
                value_str = str(value)
            value_lines.append(f"* *{field_id}*: {value_str}")

        if value_lines:
            blocks.append(
                {"type": "section", "text": {"type": "mrkdwn", "text": "\n".join(value_lines)}}
            )

    return blocks


class HITLCallbackHandler:
    """Handles HITL form callbacks and submits responses back to CAIPE."""

    def __init__(self, a2a_client, session_manager=None):
        self.a2a_client = a2a_client
        self.session_manager = session_manager

    def handle_interaction(self, payload: Dict[str, Any], slack_client) -> Optional[Dict[str, Any]]:
        """Handle a Slack interaction payload for HITL forms."""
        actions = payload.get("actions", [])
        if not actions:
            return None

        action = actions[0]
        action_id = action.get("action_id", "")

        if not action_id.startswith("hitl_form_"):
            return None

        try:
            value_data = json.loads(action.get("value", "{}"))
            form_id = value_data.get("form_id")
            action_name = value_data.get("action")
            task_id = value_data.get("task_id")
            context_id = value_data.get("context_id")

            form_values = extract_form_response(payload, form_id)

            logger.info(
                f"HITL form submission: form={form_id}, action={action_name}, "
                f"task={task_id}, values={form_values}"
            )

            channel_id = payload.get("channel", {}).get("id")
            message_ts = payload.get("message", {}).get("ts")

            if channel_id and message_ts:
                response_blocks = format_form_submission_response(
                    action=action_name,
                    form_values=form_values,
                    success=True,
                )
                slack_client.chat_update(
                    channel=channel_id,
                    ts=message_ts,
                    blocks=response_blocks,
                    text=f"Form {action_name}",
                )

            response_message = self._build_response_message(
                action_name, form_values, task_id, context_id
            )

            if context_id:
                for event in self.a2a_client.send_message_stream(
                    message_text=response_message,
                    context_id=context_id,
                ):
                    pass

            return {"response_action": "clear"}

        except Exception as e:
            logger.exception(f"Error handling HITL interaction: {e}")
            return None

    def _build_response_message(
        self, action: str, form_values: Dict[str, Any],
        task_id: str = None, context_id: str = None,
    ) -> str:
        """Build a response message to send back to CAIPE."""
        response_parts = [f"User action: {action}"]

        if form_values:
            response_parts.append("Form values:")
            for field_id, value in form_values.items():
                if isinstance(value, list):
                    value_str = ", ".join(value)
                else:
                    value_str = str(value)
                response_parts.append(f"  - {field_id}: {value_str}")

        return "\n".join(response_parts)
