{{- if and (eq (include "agent.externalSecrets.enabled" .) "false") (not .Values.secrets.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.name" . }}-secret
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
