[project]
name = "agent-graph-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "subbaksh@cisco.com" }
]
requires-python = ">=3.13"
dependencies = [
    "core",
    "langchain>=0.3.26",
    "langchain-openai>=0.3.23",
    "langgraph>=0.4.8",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "python-dotenv>=1.1.0",
]

[project.scripts]
agent-graph-gen = "agent_graph_gen:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
core = { path = "../core" }
