apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage-plugin-agent-forge.fullname" . }}
  labels:
    {{- include "backstage-plugin-agent-forge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.ports }}
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "backstage-plugin-agent-forge.selectorLabels" . | nindent 4 }}
