apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-realm
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  realm-config.json: |-
    {{- $realm := .Files.Get "realm-config.json" | fromJson -}}
    {{- $clients := list -}}
    {{- range $client := $realm.clients -}}
      {{- if eq $client.clientId "caipe-ui" -}}
        {{- $_ := set $client "redirectUris" $.Values.uiClient.redirectUris -}}
        {{- $_ := set $client "webOrigins" $.Values.uiClient.webOrigins -}}
      {{- end -}}
      {{- $clients = append $clients $client -}}
    {{- end -}}
    {{- $_ := set $realm "clients" $clients -}}
    {{- $realm | toPrettyJson | nindent 4 }}
