apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-openid-configuration
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  openid-configuration-override.json: |-
    {{- .Files.Get "openid-configuration-override.json" | nindent 4 }}
