apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-realm
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  realm-config.json: |-
    {{- .Files.Get "realm-config.json" | nindent 4 }}
