{{- if and .Values.database.enabled .Values.database.externalSecret.enabled }}
apiVersion: external-secrets.io/{{ .Values.externalSecretsApiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "keycloak.fullname" . }}-db
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.database.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.database.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.database.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.database.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.database.existingSecretPasswordKey }}
      remoteRef:
        key: {{ .Values.database.externalSecret.remoteRef.key }}
        property: {{ .Values.database.externalSecret.remoteRef.property }}
{{- end }}
