// AUTO-GENERATED by scripts/extract-rbac-resources.py — do not edit
// Generated from the Keycloak resource catalog by scripts/extract-rbac-resources.py.
//
// Catalog of (resource, scope) pairs referenced by either runtime (TS or Py).
// Used by scripts/validate-realm-config.py to assert realm-config.json completeness.
//
// To regenerate: `python3 scripts/extract-rbac-resources.py`

export const KEYCLOAK_RESOURCE_CATALOG = {
  admin_ui: { scopes: ["admin", "view"] as const },
} as const;

export type KeycloakResourceName = keyof typeof KEYCLOAK_RESOURCE_CATALOG;
