[project]
name = "mcp-argocd"
version = "0.1.0"
description = "ArgoCD MCP Server"
license = "Apache-2.0"
authors = [
  { name = "Sri Aradhyula", email = "sraradhy@cisco.com" }
]
readme = "README.md"
requires-python = ">=3.13"

[tool.poetry.scripts]
mcp-argocd = "mcp_argocd.__main__:main"

[tool.setuptools]
packages = ["mcp-argocd"]

[tool.poetry.dependencies]
python = ">=3.13,<4.0"
httpx = ">=0.24.0"
python-dotenv = ">=1.0.0"
pydantic = ">=2.0.0"
mcp = ">=1.9.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"