[project]
name = "mcp-argocd"
version = "0.1.0"
description = "ArgoCD MCP Server"
license = "Apache-2.0"
authors = [
  { name = "Sri Aradhyula", email = "sraradhy@cisco.com" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "httpx>=0.24.0",
  "python-dotenv>=1.0.0",
  "pydantic>=2.0.0",
  "mcp>=1.9.0",
]

[project.scripts]
mcp-argocd = "mcp_argocd.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"