[project]
name = "mcp_victorops_mcpapi"
version = "0.1.0"
description = "victorops MCP Server"
license = "Apache-2.0"
authors = [
  { name = "Ismael Papa", email = "ipapa@cisco.com" }
]
readme = "README.md"
requires-python = ">=3.13.2"

[tool.poetry.scripts]
mcp_argocd = "mcp_victorops_mcpapi.server:main" #mcp_victorops ??

[tool.setuptools]
packages = ["mcp_victorops_mcpapi"]

[tool.poetry.dependencies]
python = ">=3.13,<4.0"
httpx = ">=0.24.0"
python-dotenv = ">=1.0.0"
pydantic = ">=2.0.0"
mcp = ">=1.9.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"