replicaCount: 1

image:
  repository: ghcr.io/cnoe-io/agent-backstage
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

env:
  - name: BACKSTAGE_API_KEY
    value: ""
  - name: BACKSTAGE_API_URL
    value: ""

nodeSelector: {}
tolerations: []
affinity: {} 