apiVersion: v1
kind: Service
metadata:
  name: {{ include "openfga.fullname" . }}
  labels:
    {{- include "openfga.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: playground
      port: {{ .Values.service.playgroundPort }}
      targetPort: playground
      protocol: TCP
  selector:
    {{- include "openfga.selectorLabels" . | nindent 4 }}
