services:
  ####################################################################################################
  #                                 AI Platform Engineer A2A P2P                                  #
  ####################################################################################################
  platform-engineer-p2p:
    build:
      context: ../
      dockerfile: build/Dockerfile
    container_name: platform-engineer-p2p
    restart: unless-stopped
    volumes:
      - ../.env:/app/.env
      - ../prompt_config.yaml:/app/prompt_config.yaml
      # Mount only code that changes during development
      - ../ai_platform_engineering/multi_agents:/app/ai_platform_engineering/multi_agents
      - ../ai_platform_engineering/utils:/app/ai_platform_engineering/utils
    depends_on:
      - agent-weather-p2p
      - agent-petstore-p2p
    profiles:
      - p2p
    env_file:
      - ../.env
    ports:
      # Expose the AI Platform Engineer agent on port 8000
      - "8000:8000"
    environment:
      - A2A_TRANSPORT=p2p
      - WEATHER_AGENT_HOST=agent-weather-p2p
      - PETSTORE_AGENT_HOST=agent-petstore-p2p
    command: platform-engineer

  ####################################################################################################
  #                                 AI Platform Engineer A2A SLIM                                  #
  ####################################################################################################
  platform-engineer-slim:
    build:
      context: ../
      dockerfile: build/Dockerfile
    container_name: platform-engineer-slim
    restart: unless-stopped
    volumes:
      - ../.env:/app/.env
      - ../prompt_config.yaml:/app/prompt_config.yaml
      # Mount only code that changes during development
      - ../ai_platform_engineering/multi_agents:/app/ai_platform_engineering/multi_agents
      - ../ai_platform_engineering/utils:/app/ai_platform_engineering/utils
    profiles:
      - slim
    depends_on:
      - slim-dataplane
      - agent-weather-slim
      - agent-petstore-slim
    env_file:
      - ../.env
    ports:
      # Expose the AI Platform Engineer agent on port 8000
      - "8000:8000"
    environment:
      - A2A_TRANSPORT=slim
      - WEATHER_AGENT_HOST=agent-weather-slim
      - PETSTORE_AGENT_HOST=agent-petstore-slim
    command: platform-engineer

  ####################################################################################################
  #                                            SLIM Dataplane and control plane                      #
  ####################################################################################################
  slim-dataplane:
    image: ghcr.io/agntcy/slim:0.3.15
    container_name: slim-dataplane
    restart: unless-stopped
    profiles:
      - slim
    ports:
      - "46357:46357"
    environment:
      - PASSWORD=${SLIM_GATEWAY_PASSWORD:-dummy_password}
      - CONFIG_PATH=/config.yaml
    volumes:
      - ../slim-config.yaml:/config.yaml
    command: ["/slim", "--config", "/config.yaml"]
  slim-control-plane:
    image: ghcr.io/agntcy/slim/control-plane:0.0.1
    container_name: slim-control-plane
    restart: unless-stopped
    profiles:
      - slim
      - slim-tracing
    ports:
      - "50051:50051"
      - "50052:50052"
    environment:
      - PASSWORD=${SLIM_GATEWAY_PASSWORD:-dummy_password}
      - CONFIG_PATH=/config.yaml
    volumes:
      - ../slim-config.yaml:/config.yaml
    command: ["/slim", "--config", "/config.yaml"]

  ####################################################################################################
  #                                      AGENT WEATHER A2A over SLIM                                 #
  ####################################################################################################
  agent-weather-slim:
    build:
      context: ../ai_platform_engineering/agents/weather
      dockerfile: build/Dockerfile.a2a
    container_name: agent-weather-slim
    restart: unless-stopped
    profiles:
      - slim
    depends_on:
      - slim-dataplane
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.env:/app/.env
      - ../ai_platform_engineering/agents/weather/agent_weather:/app/agent_weather
      - ../ai_platform_engineering/agents/weather/clients:/app/clients
    ports:
      - "8009:8000"
    environment:
      - A2A_TRANSPORT=slim
      - MCP_MODE=${MCP_MODE:-http}

  ####################################################################################################
  #                                      AGENT WEATHER A2A P2P                                       #
  ####################################################################################################
  agent-weather-p2p:
    build:
      context: ../ai_platform_engineering/agents/weather
      dockerfile: build/Dockerfile.a2a
    container_name: agent-weather-p2p
    restart: unless-stopped
    profiles:
      - p2p
    volumes:
      - ../.env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
      - ../ai_platform_engineering/agents/weather/agent_weather:/app/agent_weather
      - ../ai_platform_engineering/agents/weather/clients:/app/clients
    ports:
      - "8009:8000"
    environment:
      - A2A_TRANSPORT=p2p
      - MCP_MODE=${MCP_MODE:-http}
      - MCP_PORT=8000
      - MCP_HOST=mcp-weather

  ####################################################################################################
  #                                      AGENT PETSTORE A2A over SLIM                                 #
  ####################################################################################################
  agent-petstore-slim:
    build:
      context: ../ai_platform_engineering/agents/template
      dockerfile: build/Dockerfile.a2a
    container_name: agent-petstore-slim
    restart: unless-stopped
    profiles:
      - slim
    depends_on:
      - slim-dataplane
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.env:/app/.env
      - ../ai_platform_engineering/agents/template/agent_petstore:/app/agent_petstore
      - ../ai_platform_engineering/agents/template/clients:/app/clients
    ports:
      - "8010:8000"
    environment:
      - A2A_TRANSPORT=slim
      - MCP_MODE=${MCP_MODE:-http}

  ####################################################################################################
  #                                      AGENT PETSTORE A2A P2P                                       #
  ####################################################################################################
  agent-petstore-p2p:
    build:
      context: ../ai_platform_engineering/agents/template
      dockerfile: build/Dockerfile.a2a
    container_name: agent-petstore-p2p
    restart: unless-stopped
    profiles:
      - p2p
    volumes:
      - ../.env:/app/.env
      - ../ai_platform_engineering/agents/template/agent_petstore:/app/agent_petstore
      - ../ai_platform_engineering/agents/template/clients:/app/clients
    ports:
      - "8010:8000"
    environment:
      - A2A_TRANSPORT=p2p
      - MCP_MODE=http
      - MCP_PORT=8000
      - MCP_HOST=mcp-petstore
      - MCP_API_URL=https://petstore.swagger.io/v2
      - MCP_API_KEY=your_api_key_here # Dummy key for demo server
