version: '3.8'

services:
  agent-petstore-p2p:
    profiles: ["mission2-dev", "mission3-dev"]
    build:
      context: ../ai_platform_engineering/agents/template
      dockerfile: build/Dockerfile.a2a
    image: local/agent-petstore:latest
    volumes:
      - ../.env:/app/.env
      # Mount only code that changes during development
      - ../ai_platform_engineering/agents/template/agent_petstore:/app/agent_petstore
      - ../ai_platform_engineering/agents/template/clients:/app/clients

  agent-petstore-slim:
    profiles: ["mission3-dev"]
    build:
      context: ../ai_platform_engineering/agents/template
      dockerfile: build/Dockerfile.a2a
    image: local/agent-petstore:latest
    volumes:
      - ../.env:/app/.env
      # Mount only code that changes during development
      - ../ai_platform_engineering/agents/template/agent_petstore:/app/agent_petstore
      - ../ai_platform_engineering/agents/template/clients:/app/clients

  platform-engineer-p2p:
    profiles: ["mission3-dev"]
    build:
      context: ../
      dockerfile: build/Dockerfile
    image: local/platform-engineer:latest
    volumes:
      - ../.env:/app/.env
      - ../prompt_config.yaml:/app/prompt_config.yaml
      # Mount only code that changes during development
      - ../ai_platform_engineering/multi_agents:/app/ai_platform_engineering/multi_agents
      - ../ai_platform_engineering/utils:/app/ai_platform_engineering/utils

  platform-engineer-slim:
    profiles: ["mission3-dev"]
    build:
      context: ../
      dockerfile: build/Dockerfile
    image: local/platform-engineer:latest
    volumes:
      - ../.env:/app/.env
      - ../prompt_config.yaml:/app/prompt_config.yaml
      # Mount only code that changes during development
      - ../ai_platform_engineering/multi_agents:/app/ai_platform_engineering/multi_agents
      - ../ai_platform_engineering/utils:/app/ai_platform_engineering/utils

  agent-weather-slim:
    profiles: ["mission3-dev"]
    build:
      context: ../ai_platform_engineering/agents/weather
      dockerfile: build/Dockerfile.a2a
    image: local/agent-weather:latest
    volumes:
      - ../.env:/app/.env
      - ../ai_platform_engineering/agents/weather/agent_weather:/app/agent_weather
      - ../ai_platform_engineering/agents/weather/clients:/app/clients

  agent-weather-p2p:
    profiles: ["mission3-dev"]
    build:
      context: ../ai_platform_engineering/agents/weather
      dockerfile: build/Dockerfile.a2a
    image: local/agent-weather:latest
    volumes:
      - ../.env:/app/.env
      - ../ai_platform_engineering/agents/weather/agent_weather:/app/agent_weather
      - ../ai_platform_engineering/agents/weather/clients:/app/clients