services:
  ####################################################################################################
  #                                    AI Platform Engineer A2A P2P                                  #
  ####################################################################################################
  platform-engineer-p2p:
    image: ghcr.io/cnoe-io/ai-platform-engineering:${IMAGE_TAG:-stable}
    container_name: platform-engineer-p2p
    volumes:
      - ../.env:/app/.env
      - ../prompt_config.yaml:/app/prompt_config.yaml
    depends_on:
      - agent-weather-p2p
      - agent-petstore-p2p
    profiles:
      - p2p
    env_file:
      - ../.env
    ports:
      # Expose the AI Platform Engineer agent on port 8000
      - "8000:8000"
    environment:
      - A2A_TRANSPORT=p2p
      - WEATHER_AGENT_HOST=agent-weather-p2p
      - PETSTORE_AGENT_HOST=agent-petstore-p2p
    command: platform-engineer

  ####################################################################################################
  #                                   AI Platform Engineer A2A SLIM                                  #
  ####################################################################################################
  platform-engineer-slim:
    image: ghcr.io/cnoe-io/ai-platform-engineering:${IMAGE_TAG:-stable}
    container_name: platform-engineer-slim
    volumes:
      - ../.env:/app/.env
      - ../prompt_config.yaml:/app/prompt_config.yaml
    profiles:
      - slim
    depends_on:
      - slim-dataplane
      - agent-weather-slim
      - agent-petstore-slim
    env_file:
      - ../.env
    ports:
      # Expose the AI Platform Engineer agent on port 8000
      - "8000:8000"
    environment:
      - A2A_TRANSPORT=slim
      - WEATHER_AGENT_HOST=agent-weather-slim
      - PETSTORE_AGENT_HOST=agent-petstore-slim
    command: platform-engineer

  ####################################################################################################
  #                                 SLIM Dataplane and control plane                                 #
  ####################################################################################################
  slim-dataplane:
    image: ghcr.io/agntcy/slim:0.3.15
    container_name: slim-dataplane
    profiles:
      - slim
    ports:
      - "46357:46357"
    environment:
      - PASSWORD=${SLIM_GATEWAY_PASSWORD:-dummy_password}
      - CONFIG_PATH=/config.yaml
    volumes:
      - ../slim-config.yaml:/config.yaml
    command: ["/slim", "--config", "/config.yaml"]
  slim-control-plane:
    image: ghcr.io/agntcy/slim/control-plane:0.0.1
    container_name: slim-control-plane
    profiles:
      - slim
      - slim-tracing
    ports:
      - "50051:50051"
      - "50052:50052"
    environment:
      - PASSWORD=${SLIM_GATEWAY_PASSWORD:-dummy_password}
      - CONFIG_PATH=/config.yaml
    volumes:
      - ../slim-config.yaml:/config.yaml
    command: ["/slim", "--config", "/config.yaml"]

  ####################################################################################################
  #                                      AGENT WEATHER A2A over SLIM                                 #
  ####################################################################################################
  agent-weather-slim:
    image: ghcr.io/cnoe-io/agent-weather:${IMAGE_TAG:-stable}
    container_name: agent-weather-slim
    profiles:
      - slim
    depends_on:
      - slim-dataplane
    volumes:
      - ../.env:/app/.env
    ports:
      - "8009:8000"
    environment:
      - A2A_TRANSPORT=slim
      - MCP_MODE=${MCP_MODE:-http}

  ####################################################################################################
  #                                      AGENT WEATHER A2A P2P                                       #
  ####################################################################################################
  agent-weather-p2p:
    image: ghcr.io/cnoe-io/agent-weather:${IMAGE_TAG:-stable}
    container_name: agent-weather-p2p
    profiles:
      - p2p
    volumes:
      - ../.env:/app/.env
    ports:
      - "8009:8000"
    environment:
      - A2A_TRANSPORT=p2p
      - MCP_MODE=${MCP_MODE:-http}
      - MCP_PORT=8000
      - MCP_HOST=mcp-weather

  ####################################################################################################
  #                                      AGENT PETSTORE A2A over SLIM                                #
  ####################################################################################################
  agent-petstore-slim:
    image: ghcr.io/cnoe-io/agent-template:${IMAGE_TAG:-stable}
    container_name: agent-petstore-slim
    profiles:
      - slim
    depends_on:
      - slim-dataplane
    volumes:
      - ../.env:/app/.env
    ports:
      - "8010:8000"
    environment:
      - A2A_TRANSPORT=slim
      - MCP_MODE=${MCP_MODE:-http}

  ####################################################################################################
  #                                      AGENT PETSTORE A2A P2P                                      #
  ####################################################################################################
  agent-petstore-p2p:
    image: ghcr.io/cnoe-io/agent-template:${IMAGE_TAG:-stable}
    container_name: agent-petstore-p2p
    profiles:
      - p2p
    volumes:
      - ../.env:/app/.env
    ports:
      - "8010:8000"
    environment:
      - A2A_TRANSPORT=p2p
      - MCP_MODE=${MCP_MODE:-http}
