services:
  ####################################################################################################
  #                                 AI Platform Engineer A2A P2P                                  #
  ####################################################################################################
  platform-engineer-p2p:
    image: ghcr.io/cnoe-io/ai-platform-engineering:latest
    pull_policy: always
    container_name: platform-engineer-p2p
    restart: unless-stopped
    volumes:
      - ../.env:/app/.env
      - ../prompt_config.yaml:/app/prompt_config.yaml
    depends_on:
      - agent-weather-p2p
      - agent-github-p2p
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    environment:
      - A2A_TRANSPORT=p2p
      - WEATHER_AGENT_HOST=agent-weather-p2p
      - GITHUB_AGENT_HOST=agent-github-p2p
      - ENABLE_TRACING=${ENABLE_TRACING:-false}
      - ENABLE_WEATHER_AGENT=true
      - LANGFUSE_TRACING_ENABLED=${LANGFUSE_TRACING_ENABLED:-True}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-NOT_SET}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-NOT_SET}
      - LANGFUSE_HOST=${LANGFUSE_HOST:-https://langfuse.dev.outshift.io}
      - LANGFUSE_SESSION_ID=${LANGFUSE_SESSION_ID:-platform-engineer}
      - LANGFUSE_USER_ID=${LANGFUSE_USER_ID:-platform-engineer}

    command: platform-engineer

  ####################################################################################################
  #                                      AGENT WEATHER A2A P2P                                       #
  ####################################################################################################
  agent-weather-p2p:
    image: ghcr.io/cnoe-io/agent-weather:latest
    pull_policy: always
    container_name: agent-weather-p2p
    restart: unless-stopped
    volumes:
      - ../.env:/app/.env
    ports:
      - "8010:8000"
    environment:
      - A2A_TRANSPORT=p2p
      - MCP_MODE=http
      - MCP_HOST=https://weather.outshift.io/mcp
      - ENABLE_TRACING=${ENABLE_TRACING:-false}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-NOT_SET}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-NOT_SET}
      - LANGFUSE_HOST=${LANGFUSE_HOST:-https://langfuse.dev.outshift.io}
      - LANGFUSE_SESSION_ID=${LANGFUSE_SESSION_ID:-platform-engineer}
      - LANGFUSE_USER_ID=${LANGFUSE_USER_ID:-platform-engineer}

  ####################################################################################################
  #                                      AGENT GITHUB A2A P2P                                        #
  ####################################################################################################
  agent-github-p2p:
    image: ghcr.io/cnoe-io/agent-github:a2a-latest
    pull_policy: always
    container_name: agent-github-p2p
    user: root
    volumes:
      - ../.env:/app/.env
    ports:
      - "8004:8000"
    environment:
      - A2A_TRANSPORT=p2p
      - MCP_MODE=http
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - ENABLE_TRACING=${ENABLE_TRACING:-false}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-NOT_SET}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-NOT_SET}
      - LANGFUSE_HOST=${LANGFUSE_HOST:-https://langfuse.dev.outshift.io}
      - LANGFUSE_SESSION_ID=${LANGFUSE_SESSION_ID:-platform-engineer}
      - LANGFUSE_USER_ID=${LANGFUSE_USER_ID:-platform-engineer}