apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentgateway.fullname" . }}-config
  labels:
    {{- include "agentgateway.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ tpl (toYaml .Values.config) . | indent 4 }}
