#!/usr/bin/env bash
# caipe-catalog.sh — Claude Code SessionStart hook
#
# Fetches the CAIPE skills catalog from the gateway and injects a compact
# index into Claude's context as `additionalContext`. Claude sees what
# skills are available and can invoke them via the live caipe-skills.py
# helper or via locally-installed copies.
#
# This file is shipped from the chart at:
#   charts/ai-platform-engineering/data/skills/caipe-catalog.sh
#
# `install.sh` curls it from the gateway, rewrites the {{BASE_URL}}
# placeholder to the deployment's public origin, drops it at
# ~/.<agent>/hooks/caipe-catalog.sh, and registers a SessionStart hook
# in the agent's settings.json. End users do not edit this file.
#
# CONFIG resolution for the gateway URL (first match wins):
#   1. CAIPE_BASE_URL env var (per-shell override)
#   2. ~/.config/caipe/config.json -> base_url (persistent user setting)
#   3. CAIPE_SKILLS_GATEWAY_DEFAULT_URL env var (operator-wide default)
#   4. {{BASE_URL}} below (rewritten by install.sh; left as the literal
#      placeholder when this file is run directly from the repo, in which
#      case the hook fails closed with a clear message)
#
# API key resolution (first match wins):
#   1. CAIPE_CATALOG_KEY env var
#   2. ~/.config/caipe/config.json -> api_key
#
# Failure modes are deliberately silent at the curl/parse level (we
# never want a slow gateway to block session boot) and surface as a
# short, human-readable additionalContext string so Claude can pass
# along the diagnostic to the user without aborting startup.
#
# Output (Claude Code hook protocol):
#   { "hookSpecificOutput": { "hookEventName": "SessionStart",
#                             "additionalContext": "..." } }

set -euo pipefail

# Install-time substitution; install.sh rewrites this to the gateway origin.
DEFAULT_BASE_URL="{{BASE_URL}}"

CONFIG_FILE="${HOME}/.config/caipe/config.json"
HOOK_TIMEOUT_SECS="${CAIPE_HOOK_TIMEOUT:-3}"
RAW_PAGE_SIZE="${CAIPE_HOOK_PAGE_SIZE:-50}"

# Defend against runaway PAGE_SIZE — Claude Code caps additionalContext
# at ~10K chars, and the catalog can contain hundreds of skills. Anything
# above 100 risks exceeding the cap with low value to the agent (skills
# beyond the first ~50 are usually noise for any single session).
if ! [[ "$RAW_PAGE_SIZE" =~ ^[0-9]+$ ]] || [ "$RAW_PAGE_SIZE" -lt 1 ]; then
  PAGE_SIZE=50
elif [ "$RAW_PAGE_SIZE" -gt 100 ]; then
  PAGE_SIZE=100
else
  PAGE_SIZE="$RAW_PAGE_SIZE"
fi

read_config_field() {
  local field="$1"
  if [ ! -r "$CONFIG_FILE" ]; then
    return 1
  fi
  if ! command -v python3 >/dev/null 2>&1; then
    return 1
  fi
  # Pass the field through env to avoid shell quoting issues. Pure JSON
  # parsing in Python — no PyYAML, no jq dependency.
  CAIPE_CFG="$CONFIG_FILE" CAIPE_FIELD="$field" python3 -c '
import json, os, sys
try:
    with open(os.environ["CAIPE_CFG"], encoding="utf-8") as f:
        cfg = json.load(f)
    val = cfg.get(os.environ["CAIPE_FIELD"], "")
    if val:
        print(val)
except Exception:
    sys.exit(1)
' 2>/dev/null
}

# Base URL chain. Config wins over env vars (consistent with
# caipe-skills.py): a stray exported CAIPE_BASE_URL silently shadowing
# config is a confusing failure mode.
BASE_URL=""
if [ -n "${CAIPE_BASE_URL:-}" ]; then
  BASE_URL="$CAIPE_BASE_URL"
fi
if [ -z "$BASE_URL" ]; then
  BASE_URL="$(read_config_field base_url || true)"
fi
if [ -z "$BASE_URL" ] && [ -n "${CAIPE_SKILLS_GATEWAY_DEFAULT_URL:-}" ]; then
  BASE_URL="$CAIPE_SKILLS_GATEWAY_DEFAULT_URL"
fi
if [ -z "$BASE_URL" ] && [ "$DEFAULT_BASE_URL" != "{{BASE_URL}}" ]; then
  BASE_URL="$DEFAULT_BASE_URL"
fi

API_KEY="${CAIPE_CATALOG_KEY:-}"
if [ -z "$API_KEY" ]; then
  API_KEY="$(read_config_field api_key || true)"
fi

emit_context() {
  # Read text from heredoc on stdin, wrap into Claude's hook envelope.
  python3 -c '
import json, sys
print(json.dumps({
    "hookSpecificOutput": {
        "hookEventName": "SessionStart",
        "additionalContext": sys.stdin.read()
    }
}))
' <<<"$1"
}

if [ -z "$BASE_URL" ]; then
  emit_context "[caipe-catalog hook] No CAIPE base_url configured. Set base_url in ~/.config/caipe/config.json, export CAIPE_BASE_URL, or re-run install.sh from your gateway. Catalog unavailable this session."
  exit 0
fi

if [ -z "$API_KEY" ]; then
  emit_context "[caipe-catalog hook] No CAIPE_CATALOG_KEY configured. Catalog unavailable this session — install your gateway-issued key into ~/.config/caipe/config.json. Existing locally-installed skills still work."
  exit 0
fi

# Strip trailing slash for clean URL composition.
BASE_URL="${BASE_URL%/}"
CATALOG_URL="${BASE_URL}/api/skills?page=1&page_size=${PAGE_SIZE}"

# Hard timeout — never block session boot on a slow / unreachable gateway.
RAW="$(curl -fsS \
  --max-time "$HOOK_TIMEOUT_SECS" \
  -H "X-Caipe-Catalog-Key: $API_KEY" \
  "$CATALOG_URL" 2>/dev/null)" || RAW=""

if [ -z "$RAW" ]; then
  emit_context "[caipe-catalog hook] Could not reach CAIPE catalog at ${BASE_URL} within ${HOOK_TIMEOUT_SECS}s. Skills are still available via /skills if installed locally."
  exit 0
fi

# Compact-index renderer in Python so we can keep deterministic sort,
# precise truncation, and clean handling of multi-line descriptions.
export RAW BASE_URL
INDEX="$(python3 - <<'PY'
import json
import os
import sys

raw = os.environ.get("RAW", "")
try:
    data = json.loads(raw)
except Exception as exc:
    print(f"[caipe-catalog hook] Catalog parse failed: {exc}")
    sys.exit(0)

skills = data.get("skills", []) or []
if not skills:
    print("[caipe-catalog hook] CAIPE catalog returned 0 skills.")
    sys.exit(0)

base_url = os.environ.get("BASE_URL", "")

lines = []
lines.append("# CAIPE Skills Catalog (live, fetched at session start)")
lines.append("")
lines.append(f"Gateway: {base_url}  ·  {len(skills)} skill(s) available")
lines.append("")
lines.append("To browse / fetch skills not installed locally:")
lines.append("  /skills <query>            # interactive live search")
lines.append("  /update-skills             # refresh local copies from catalog")
lines.append("")
lines.append("Catalog index:")
lines.append("")


def short_desc(d: str, n: int = 140) -> str:
    """Single-line, length-capped description suitable for an index row."""
    d = (d or "").strip().split("\n")[0]
    return d if len(d) <= n else d[: n - 1].rstrip() + "..."


for s in sorted(skills, key=lambda x: x.get("name", "")):
    name = s.get("name", "?")
    desc = short_desc(s.get("description", ""))
    lines.append(f"  - {name}: {desc}")

out = "\n".join(lines)

# Claude Code caps additionalContext at ~10K chars; leave 500 chars of
# headroom for the JSON envelope and any normalization Claude does.
CAP = 9500
if len(out) > CAP:
    truncated = out[:CAP]
    # Don't cut mid-line — find the last newline before the cap.
    truncated = truncated.rsplit("\n", 1)[0]
    shown = truncated.count("\n") - 8  # subtract header lines
    truncated += (
        f"\n\n[truncated: catalog has {len(skills)} skills, only the first "
        f"~{shown} shown. Use /skills to search the rest, or set "
        f"CAIPE_HOOK_PAGE_SIZE to control how many appear here.]"
    )
    out = truncated

print(out)
PY
)"

emit_context "$INDEX"
