{{- if .Values.clientProfiles }}{{ include "supervisorAgent.validateClientProfiles" . }}{{- end -}}
{{- /* Default supervisor deployment */ -}}
{{ include "supervisorAgent.deployment" (dict "root" . "profileName" "" "profile" nil) }}
{{- /* Profile supervisor deployments */ -}}
{{- range $profileName, $profile := .Values.clientProfiles }}
---
{{ include "supervisorAgent.deployment" (dict "root" $ "profileName" $profileName "profile" $profile) }}
{{- end }}
