{{- /* Default supervisor service */ -}}
{{ include "supervisorAgent.service" (dict "root" . "profileName" "") }}
{{- /* Profile supervisor services */ -}}
{{- range $profileName, $profile := .Values.clientProfiles }}
---
{{ include "supervisorAgent.service" (dict "root" $ "profileName" $profileName) }}
{{- end }}
