name: helm push

on:
  push:
    branches:
      - main
      - "refs/tags/v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  helm-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Simplified to latest stable version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Helm
        uses: azure/setup-helm@v4 # Simplified to latest stable version
        with:
          version: "3.12.1" # Default Helm version

      - name: Helm lint
        run: helm lint deployment/helm/agent-template --with-subcharts

      - name: Package and Push Helm Chart
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        run: |
          # Extract the version from Chart.yaml
          CHART_VERSION=$(grep '^version:' deployment/helm/agent-template/Chart.yaml | awk '{print $2}')

          # Package and push the Helm chart
          helm package deployment/helm/agent-template --dependency-update --version $CHART_VERSION
          helm push agent-template-$CHART_VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}/helm
