# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Incident models for the API"""
from typing import List, Optional , Literal
from pydantic import BaseModel


class Target(BaseModel):
    type: Literal["User","EscalationPolicy"]
    slug: str

class IncidentCreate(BaseModel):
    summary: str
    details: str
    userName: str
    targets: List[Target]
    isMultiResponder: Optional[bool] = None




