{{- if and .Values.redis.enabled (or .Values.global.profiles.knowledgeBase .Values.global.profiles.graphRag .Values.global.profiles.nexigraph) }}
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ include "graphrag.fullname" . }}-redis
      namespace: {{ .Release.Namespace }}
    spec:
      type: ClusterIP
      ports:
        - port: 6379
          targetPort: 6379
      selector:
        app: redis
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: {{ include "graphrag.fullname" . }}-redis-server
      namespace: {{ .Release.Namespace }}
    spec:
      serviceName: {{ include "graphrag.fullname" . }}-redis
      replicas: 1
      selector:
        matchLabels:
          app: redis
      template:
        metadata:
          labels:
            app: redis
        spec:
          terminationGracePeriodSeconds: 10
          containers:
            - name: redis
              image: "{{ .Values.redis.imageRepository }}:{{ .Values.redis.tagversion }}"
              imagePullPolicy: {{ .Values.redis.imagePullPolicy }}
              command:
                - redis-server
              ports:
                - name: redis
                  containerPort: 6379
{{- end }}