{{- if and .Values.redis.enabled .Values.redis.persistence.enabled (or .Values.global.profiles.knowledgeBase .Values.global.profiles.graphRag .Values.global.profiles.nexigraph) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "graphrag.fullname" . }}-redis
  labels:
    {{- include "graphrag.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
  {{- if .Values.redis.persistence.storageClass }}
  {{- if (eq "-" .Values.redis.persistence.storageClass) }}
  storageClassName: ""
  {{- else if ne .Values.redis.persistence.storageClass "" }}
  storageClassName: "{{ .Values.redis.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
