[project]
name = "core"
version = "0.1.0"
description = "Core library for NexiGraph, a graph-based knowledge management system"
readme = "README.md"
authors = [
    { email = "subbaksh@cisco.com" }
]
requires-python = ">=3.13"
dependencies = [
    "cymple>=0.12.0",
    "neo4j>=5.28.1",
    "pydantic>=2.11.7",
    "redis>=6.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
