{{- if and (not .Values.serviceToken.existingSecret) .Values.serviceToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scheduler.serviceTokenSecretName" . }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.serviceToken.existingSecretKey | default "token" }}: {{ .Values.serviceToken.value | quote }}
{{- end }}
