#!/usr/bin/env python3
"""
scripts/append-pending-rbac-entries.py

Spec 102 / T037 follow-up — append matrix entries for legacy `requireAdmin`
call sites that aren't yet covered by `tests/rbac/rbac-matrix.yaml`.

These are admin-gated routes outside Phase 3's primary scope (Admin UI). They
need a matrix entry tagged `migration_status: pending` so:

  1. The Phase 3 deprecation guard (`scripts/check-no-new-requireAdmin.sh`)
     accepts them as known-pending.
  2. The Phase 4 matrix-driver test (T038) auto-skips them via `xit()` until
     a future phase migrates them to `requireRbacPermission`.

Idempotent: only appends entries between BEGIN/END markers and only when the
generated block differs from what's already present.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MATRIX_PATH = ROOT / "tests" / "rbac" / "rbac-matrix.yaml"

BEGIN_MARK = "  # >>> BEGIN auto-generated by scripts/append-pending-rbac-entries.py"
END_MARK = "  # <<< END auto-generated by scripts/append-pending-rbac-entries.py"

# (method, path, resource, scope, notes)
PENDING: list[tuple[str, str, str, str, str]] = [
    ("POST", "/api/agent-skills/import-github", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (catalog admin)"),
    ("POST", "/api/llm-models", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (LLM provider config)"),
    ("PUT", "/api/llm-models", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (LLM provider config)"),
    ("DELETE", "/api/llm-models", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (LLM provider config)"),
    ("POST", "/api/policies", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (policy authoring)"),
    ("PUT", "/api/policies", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (policy authoring)"),
    ("DELETE", "/api/policies", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (policy authoring)"),
    ("POST", "/api/skill-hubs", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (skill-hub catalog)"),
    ("PATCH", "/api/skill-hubs/[id]", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (skill-hub catalog)"),
    ("DELETE", "/api/skill-hubs/[id]", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (skill-hub catalog)"),
    ("POST", "/api/skill-hubs/crawl", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (skill-hub crawler)"),
    ("POST", "/api/skills/refresh", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (skill cache refresh)"),
    ("POST", "/api/task-configs/seed", "admin_ui", "admin",
     "Legacy requireAdmin gate; TODO migrate (task-config seeding)"),
]


def _id(method: str, path: str) -> str:
    slug = path.strip("/").replace("/", "-").replace("[", "").replace("]", "")
    return f"ui-bff-{method.lower()}-{slug}"


def render() -> str:
    lines: list[str] = []
    for method, path, resource, scope, notes in PENDING:
        lines.append(f"  - id: {_id(method, path)}")
        lines.append("    surface: ui_bff")
        lines.append(f"    method: {method}")
        lines.append(f"    path: {path}")
        lines.append(f"    resource: {resource}")
        lines.append(f"    scope: {scope}")
        lines.append("    migration_status: pending")
        lines.append(f"    notes: {notes}")
        lines.append("    expectations:")
        lines.append("      alice_admin:")
        lines.append("        status: 200")
        for persona in ("bob_chat_user", "carol_kb_ingestor", "dave_no_role",
                        "eve_dynamic_agent_user", "frank_service_account"):
            lines.append(f"      {persona}:")
            lines.append("        status: 403")
            lines.append("        reason: DENY_NO_CAPABILITY")
    return "\n".join(lines) + "\n"


def main() -> int:
    text = MATRIX_PATH.read_text(encoding="utf-8")
    block = render()

    if BEGIN_MARK in text and END_MARK in text:
        before, _, rest = text.partition(BEGIN_MARK)
        _, _, after = rest.partition(END_MARK)
        new_text = (
            before.rstrip("\n")
            + "\n"
            + BEGIN_MARK
            + "\n"
            + block
            + END_MARK
            + after
        )
    else:
        if "routes:" not in text:
            print(f"error: {MATRIX_PATH} has no `routes:` key", file=sys.stderr)
            return 2
        new_text = (
            text.rstrip("\n")
            + "\n"
            + BEGIN_MARK
            + "\n"
            + block
            + END_MARK
            + "\n"
        )

    if new_text == text:
        print("[append-pending-rbac-entries] no changes — matrix already up to date")
        return 0

    MATRIX_PATH.write_text(new_text, encoding="utf-8")
    print(f"[append-pending-rbac-entries] wrote {len(PENDING)} pending entries to {MATRIX_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
