#!/usr/bin/env python3
"""Extract every (resource, scope) literal from TS+Py RBAC call sites.

Spec 102 (`data-model.md` §E4). Emits ``ui/src/lib/rbac/resource-catalog.generated.ts``
which exports ``KEYCLOAK_RESOURCE_CATALOG``. Consumed by ``scripts/validate-realm-config.py``
to assert that ``deploy/keycloak/realm-config.json`` declares every resource & scope the
runtime references.

The generated file is checked in (so reviewers can see drift in PRs) and regenerated by
``make test-rbac`` before validation.
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "ui" / "src" / "lib" / "rbac" / "resource-catalog.generated.ts"

UI_GLOB = "ui/src/**/*.ts"
PY_GLOBS = (
    "ai_platform_engineering/**/*.py",
    "ai_platform_engineering/**/server.py",
)

TS_CALL_RE = re.compile(
    r"requireRbacPermission\s*\(\s*[^,]+?,\s*[\"']([a-z0-9_]+(?::[A-Za-z0-9_-]+)?)[\"']\s*,\s*[\"']([a-z_]+)[\"']",
    re.MULTILINE | re.DOTALL,
)
PY_CALL_RE = re.compile(
    r"require_rbac_permission\s*\(\s*[^,]+?,\s*[\"']([a-z0-9_]+(?::[A-Za-z0-9_-]+)?)[\"']\s*,\s*[\"']([a-z_]+)[\"']",
    re.MULTILINE | re.DOTALL,
)

HEADER = """// AUTO-GENERATED by scripts/extract-rbac-resources.py — do not edit
// Spec 102: docs/docs/specs/102-comprehensive-rbac-tests-and-completion/data-model.md §E4
//
// Catalog of (resource, scope) pairs referenced by either runtime (TS or Py).
// Used by scripts/validate-realm-config.py to assert realm-config.json completeness.
//
// To regenerate: `python3 scripts/extract-rbac-resources.py`
"""


def collect(globs, pattern):
    catalog: dict[str, set[str]] = defaultdict(set)
    for glob in globs:
        for path in REPO_ROOT.glob(glob):
            try:
                content = path.read_text()
            except (UnicodeDecodeError, PermissionError):
                continue
            for match in pattern.finditer(content):
                resource, scope = match.group(1), match.group(2)
                catalog[resource].add(scope)
    return catalog


def render(catalog: dict[str, set[str]]) -> str:
    lines = [HEADER, "export const KEYCLOAK_RESOURCE_CATALOG = {"]
    for resource in sorted(catalog):
        scopes = sorted(catalog[resource])
        scopes_str = ", ".join(json.dumps(s) for s in scopes)
        lines.append(f"  {resource}: {{ scopes: [{scopes_str}] as const }},")
    lines.append("} as const;")
    lines.append("")
    lines.append("export type KeycloakResourceName = keyof typeof KEYCLOAK_RESOURCE_CATALOG;")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    print("[extract-rbac-resources] scanning TS…")
    ts_catalog = collect([UI_GLOB], TS_CALL_RE)
    print(f"[extract-rbac-resources]   {sum(len(v) for v in ts_catalog.values())} (resource, scope) pair(s) in TS")

    print("[extract-rbac-resources] scanning Py…")
    py_catalog = collect(PY_GLOBS, PY_CALL_RE)
    print(f"[extract-rbac-resources]   {sum(len(v) for v in py_catalog.values())} (resource, scope) pair(s) in Py")

    merged: dict[str, set[str]] = defaultdict(set)
    for cat in (ts_catalog, py_catalog):
        for r, s in cat.items():
            merged[r] |= s

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(merged))
    print(f"[extract-rbac-resources] wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    print(f"[extract-rbac-resources] {len(merged)} unique resource(s), {sum(len(v) for v in merged.values())} (resource, scope) pair(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
