#!/usr/bin/env python3
"""scripts/generate-rbac-matrix-us1.py

Generate Phase 3 / US1 entries for `tests/rbac/rbac-matrix.yaml` from a
hand-curated inventory of `ui/src/app/api/{admin,dynamic-agents,mcp-servers,agents}/**/route.ts`.

The inventory was produced by reading every route file once (T035/T036 task work).
This script encodes:
  • Per-route (resource, scope) target mapping (FR-006)
  • Per-persona allow/deny expectations (matches spec.md §Personas)
  • Output is YAML ready to paste / merge into `tests/rbac/rbac-matrix.yaml`

The script is idempotent and pure: re-running it produces byte-identical output.
Hand-tuned routes (e.g. `/api/admin/teams` smoke entry) live above the generated
block under the marker `# >>> generated by scripts/generate-rbac-matrix-us1.py`.

Usage:
    python scripts/generate-rbac-matrix-us1.py                # write to YAML
    python scripts/generate-rbac-matrix-us1.py --stdout       # dump to stdout
    python scripts/generate-rbac-matrix-us1.py --check        # exit 1 if file
                                                              # would change
Linter contract: every entry produced here must satisfy
    scripts/validate-rbac-matrix.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Literal

REPO_ROOT = Path(__file__).resolve().parents[1]
MATRIX_PATH = REPO_ROOT / "tests/rbac/rbac-matrix.yaml"

# Generator markers — content between BEGIN and END is auto-managed.
BEGIN_MARK = "# >>> generated by scripts/generate-rbac-matrix-us1.py — DO NOT EDIT"
END_MARK = "# <<< end generated"

PERSONAS = (
    "alice_admin",
    "bob_chat_user",
    "carol_kb_ingestor",
    "dave_no_role",
    "eve_dynamic_agent_user",
    "frank_service_account",
)

# ─────────────────────────────────────────────────────────────────────────────
# Allow tables — per (resource, scope) which personas should pass
#
# Mirrors deploy/keycloak/realm-config.json policies + RESOURCE_ROLE_FALLBACK.
# A persona allows iff the role policy for the resource/scope binds their role.
# ─────────────────────────────────────────────────────────────────────────────

# alice has admin role → allows on every admin scope
# bob/carol/eve have chat_user → allow only on chat scopes
# dave/frank have no role → deny everywhere

# Format: (resource, scope) -> list of personas that should ALLOW (status 2xx).
ALLOW_TABLE: dict[tuple[str, str], tuple[str, ...]] = {
    # admin_ui — admin role only
    ("admin_ui", "view"): ("alice_admin",),
    ("admin_ui", "configure"): ("alice_admin",),
    ("admin_ui", "admin"): ("alice_admin",),
    ("admin_ui", "audit.view"): ("alice_admin",),
    # team — view: team_member or admin; manage: admin only
    ("team", "view"): ("alice_admin",),  # team_member persona doesn't exist yet
    ("team", "manage"): ("alice_admin",),
    # mcp_server — read: chat_user (everyone-with-role); manage: admin
    ("mcp_server", "read"): ("alice_admin", "bob_chat_user", "carol_kb_ingestor", "eve_dynamic_agent_user"),
    ("mcp_server", "manage"): ("alice_admin",),
    # dynamic_agent — view+invoke: chat_user; manage: admin
    ("dynamic_agent", "view"): ("alice_admin", "bob_chat_user", "carol_kb_ingestor", "eve_dynamic_agent_user"),
    ("dynamic_agent", "invoke"): ("alice_admin", "bob_chat_user", "carol_kb_ingestor", "eve_dynamic_agent_user"),
    ("dynamic_agent", "manage"): ("alice_admin",),
}


# ─────────────────────────────────────────────────────────────────────────────
# Route inventory — (path, method, resource, scope, notes)
#
# Sourced from the audit of ui/src/app/api/{admin,dynamic-agents,mcp-servers,agents}.
# `path` uses the URL form (Next.js dynamic segments stay as `[id]`).
# Routes that are intentionally NOT RBAC-gated (e.g. /health, /builtin-tools)
# are excluded — the matrix linter will continue to ignore them via the
# `unprotected_endpoints_allowlist` block in scripts/validate-rbac-matrix.py.
# ─────────────────────────────────────────────────────────────────────────────

Surface = Literal["ui_bff"]
Method = Literal["GET", "POST", "PUT", "PATCH", "DELETE"]


ROUTES: list[tuple[str, Method, str, str, str]] = [
    # ── /api/admin/** ────────────────────────────────────────────────────────
    ("/api/admin/users/stats", "GET", "admin_ui", "view", "Already migrated"),
    ("/api/admin/stats", "GET", "admin_ui", "view", "Already migrated"),
    ("/api/admin/stats/skills", "GET", "admin_ui", "view", "TODO migrate"),
    ("/api/admin/stats/checkpoints", "GET", "admin_ui", "view", "TODO migrate"),
    ("/api/admin/users", "GET", "admin_ui", "view", "TODO migrate"),
    ("/api/admin/users/[id]", "GET", "admin_ui", "view", "TODO migrate"),
    ("/api/admin/users/[id]", "PUT", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/users/[id]/teams", "POST", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/users/[id]/teams", "DELETE", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/users/[id]/roles", "POST", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/users/[id]/roles", "DELETE", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/users/[id]/role", "PATCH", "admin_ui", "admin", "Legacy Mongo role; TODO migrate"),
    # Teams — target migration to `team` resource per FR-006
    ("/api/admin/teams", "POST", "team", "manage", "Already partial; migrate to team#manage"),
    ("/api/admin/teams/[id]", "GET", "team", "view", "Migrate to team#view"),
    ("/api/admin/teams/[id]", "PATCH", "team", "manage", "Migrate to team#manage"),
    ("/api/admin/teams/[id]", "DELETE", "team", "manage", "Migrate to team#manage"),
    ("/api/admin/teams/[id]/roles", "GET", "team", "view", "Migrate to team#view"),
    ("/api/admin/teams/[id]/roles", "PUT", "team", "manage", "Migrate to team#manage"),
    ("/api/admin/teams/[id]/members", "POST", "team", "manage", "Migrate to team#manage"),
    ("/api/admin/teams/[id]/members", "DELETE", "team", "manage", "Migrate to team#manage"),
    ("/api/admin/teams/[id]/kb-assignments", "GET", "team", "view", "Migrate to team#view"),
    ("/api/admin/teams/[id]/kb-assignments", "PUT", "team", "manage", "Migrate to team#manage"),
    ("/api/admin/teams/[id]/kb-assignments", "DELETE", "team", "manage", "Migrate to team#manage"),
    # Slack admin
    ("/api/admin/slack/users", "GET", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/slack/users/[id]", "POST", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/slack/users/[id]", "DELETE", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/slack/channel-mappings", "GET", "admin_ui", "view", "TODO migrate"),
    ("/api/admin/slack/channel-mappings", "POST", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/slack/channel-mappings", "DELETE", "admin_ui", "admin", "TODO migrate"),
    # Roles + role-mappings
    ("/api/admin/roles", "GET", "admin_ui", "view", "TODO migrate"),
    ("/api/admin/roles", "POST", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/roles/[name]", "GET", "admin_ui", "view", "TODO migrate"),
    ("/api/admin/roles/[name]", "DELETE", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/role-mappings", "GET", "admin_ui", "view", "TODO migrate"),
    ("/api/admin/role-mappings", "POST", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/role-mappings/[id]", "DELETE", "admin_ui", "admin", "TODO migrate"),
    # Audit
    ("/api/admin/rbac-audit", "GET", "admin_ui", "audit.view", "Already migrated"),
    ("/api/admin/audit-events", "GET", "admin_ui", "audit.view", "Already migrated"),
    ("/api/admin/audit-logs", "GET", "admin_ui", "audit.view", "TODO migrate"),
    ("/api/admin/audit-logs/owners", "GET", "admin_ui", "audit.view", "TODO migrate"),
    ("/api/admin/audit-logs/export", "GET", "admin_ui", "audit.view", "TODO migrate"),
    ("/api/admin/audit-logs/[id]/messages", "GET", "admin_ui", "audit.view", "TODO migrate"),
    # NPS / feedback / metrics / migrations
    ("/api/admin/nps", "GET", "admin_ui", "view", "TODO migrate (currently withAuth)"),
    ("/api/admin/nps/campaigns", "GET", "admin_ui", "view", "TODO migrate"),
    ("/api/admin/nps/campaigns", "POST", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/nps/campaigns", "PATCH", "admin_ui", "admin", "TODO migrate"),
    ("/api/admin/feedback", "GET", "admin_ui", "view", "TODO migrate (currently withAuth)"),
    ("/api/admin/metrics", "GET", "admin_ui", "view", "TODO migrate (admin only — comment but no guard)"),
    ("/api/admin/metrics", "POST", "admin_ui", "view", "TODO migrate (batch PromQL)"),
    ("/api/admin/migrate-conversations", "POST", "admin_ui", "admin", "TODO migrate"),
    # ── /api/dynamic-agents/** ───────────────────────────────────────────────
    ("/api/dynamic-agents", "GET", "dynamic_agent", "view", "TODO migrate (currently visibility-only)"),
    ("/api/dynamic-agents", "POST", "dynamic_agent", "manage", "TODO migrate"),
    ("/api/dynamic-agents", "PUT", "dynamic_agent", "manage", "TODO migrate"),
    ("/api/dynamic-agents", "DELETE", "dynamic_agent", "manage", "TODO migrate"),
    ("/api/dynamic-agents/conversations", "GET", "dynamic_agent", "manage", "TODO migrate (admin list)"),
    ("/api/dynamic-agents/conversations/[id]/interrupt-state", "GET", "dynamic_agent", "invoke", "TODO migrate"),
    ("/api/dynamic-agents/conversations/[id]/files/list", "GET", "dynamic_agent", "invoke", "TODO migrate"),
    ("/api/dynamic-agents/conversations/[id]/files/content", "GET", "dynamic_agent", "invoke", "TODO migrate"),
    ("/api/dynamic-agents/conversations/[id]/files/content", "DELETE", "dynamic_agent", "invoke", "TODO migrate"),
    ("/api/dynamic-agents/conversations/[id]/clear", "POST", "dynamic_agent", "invoke", "TODO migrate"),
    ("/api/dynamic-agents/assistant/suggest", "POST", "dynamic_agent", "manage", "TODO migrate (assistant)"),
    ("/api/dynamic-agents/models", "GET", "dynamic_agent", "view", "TODO migrate"),
    ("/api/dynamic-agents/chat/restart-runtime", "POST", "dynamic_agent", "manage", "TODO migrate (admin op)"),
    ("/api/dynamic-agents/available", "GET", "dynamic_agent", "view", "TODO migrate (chat picker)"),
    ("/api/dynamic-agents/teams", "GET", "dynamic_agent", "view", "TODO migrate"),
    ("/api/dynamic-agents/available-subagents", "GET", "dynamic_agent", "manage", "TODO migrate"),
    ("/api/dynamic-agents/agents/[id]", "GET", "dynamic_agent", "view", "TODO migrate"),
    # ── /api/mcp-servers/** ──────────────────────────────────────────────────
    ("/api/mcp-servers", "GET", "mcp_server", "read", "TODO migrate"),
    ("/api/mcp-servers", "POST", "mcp_server", "manage", "TODO migrate"),
    ("/api/mcp-servers", "PUT", "mcp_server", "manage", "TODO migrate"),
    ("/api/mcp-servers", "DELETE", "mcp_server", "manage", "TODO migrate"),
    ("/api/mcp-servers/probe", "POST", "mcp_server", "manage", "TODO migrate"),
    # ── /api/agents/** ───────────────────────────────────────────────────────
    ("/api/agents/tools", "GET", "mcp_server", "read", "TODO migrate (chat picker)"),
]


def _route_id(path: str, method: str) -> str:
    """Stable, kebab-case id for matrix linter cross-references."""
    cleaned = path.strip("/").replace("[", "").replace("]", "").replace("/", "-")
    return f"ui-bff-{method.lower()}-{cleaned}"


def _build_expectations(resource: str, scope: str) -> dict[str, dict[str, object]]:
    """Build per-persona expectations for a (resource, scope) pair."""
    allowed_personas = ALLOW_TABLE.get((resource, scope), ())
    expectations: dict[str, dict[str, object]] = {}
    for persona in PERSONAS:
        if persona in allowed_personas:
            expectations[persona] = {"status": 200}
        else:
            expectations[persona] = {"status": 403, "reason": "DENY_NO_CAPABILITY"}
    return expectations


def render_yaml() -> str:
    """Render the generated portion (no header/footer)."""
    lines: list[str] = []
    for path, method, resource, scope, notes in ROUTES:
        rid = _route_id(path, method)
        # Anything starting with "TODO migrate" or "Migrate to" is a pending
        # row — handler still uses requireAdmin / withAuth-only and will be
        # flipped to `migrated` by the Phase 3 migration tasks (T040–T049).
        is_pending = notes.startswith("TODO migrate") or notes.startswith("Migrate to")
        lines.append(f"  - id: {rid}")
        lines.append("    surface: ui_bff")
        lines.append(f"    method: {method}")
        lines.append(f"    path: {path}")
        lines.append(f"    resource: {resource}")
        lines.append(f"    scope: {scope}")
        lines.append(f"    migration_status: {'pending' if is_pending else 'migrated'}")
        if notes:
            lines.append(f"    notes: {notes}")
        lines.append("    expectations:")
        for persona, exp in _build_expectations(resource, scope).items():
            lines.append(f"      {persona}:")
            for k, v in exp.items():
                lines.append(f"        {k}: {v}")
    return "\n".join(lines) + "\n"


def write_matrix(check_only: bool) -> int:
    text = MATRIX_PATH.read_text(encoding="utf-8")

    new_block = render_yaml()

    if BEGIN_MARK in text and END_MARK in text:
        before, _, rest = text.partition(BEGIN_MARK)
        _, _, after = rest.partition(END_MARK)
        new_text = (
            before.rstrip("\n")
            + "\n"
            + BEGIN_MARK
            + "\n"
            + new_block
            + END_MARK
            + "\n"
            + after.lstrip("\n")
        )
    else:
        # Append after the existing routes block (do not destroy hand-curated entries)
        if not text.rstrip().endswith("routes:") and "routes:" not in text:
            print(f"error: {MATRIX_PATH} has no `routes:` key", file=sys.stderr)
            return 2
        new_text = (
            text.rstrip("\n")
            + "\n"
            + BEGIN_MARK
            + "\n"
            + new_block
            + END_MARK
            + "\n"
        )

    if check_only:
        if new_text != text:
            print(f"{MATRIX_PATH} would be modified — run scripts/generate-rbac-matrix-us1.py")
            return 1
        return 0

    MATRIX_PATH.write_text(new_text, encoding="utf-8")
    print(f"wrote {len(ROUTES)} routes × {len(PERSONAS)} personas to {MATRIX_PATH}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stdout", action="store_true", help="print generated YAML to stdout")
    parser.add_argument("--check", action="store_true", help="exit 1 if file would change")
    args = parser.parse_args()

    if args.stdout:
        sys.stdout.write(render_yaml())
        return 0

    return write_matrix(check_only=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
