[project]
name = "slack-mcp"
version = "0.1.0"
description = "An MCP (Model Context Protocol) server that integrates with the Slack API, enabling agentic tools to interact with Slack through natural language."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "mcp[cli]>=1.4.1",
    "slack-sdk>=3.27.1",
    "fastmcp>=0.1.0",
    "colorama>=0.4.6",
    "smolagents>=0.1.0",
    "litellm>=1.0.0",
]

[tool.setuptools]
packages = ["api", "models", "tools", "utils"]
package-dir = {"" = "."}

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
namespace_packages = true
explicit_package_bases = true
ignore_missing_imports = true

# Exclude the main package name from checks
exclude = [
    "^slack-mcp$",
]

# Focus only on individual modules
[[tool.mypy.overrides]]
module = ["api.*", "models.*", "tools.*", "utils.*"]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["server"]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["mcp.*", "dotenv.*", "httpx.*", "slack_sdk.*"]
ignore_missing_imports = true