import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Source_Sans_3, IBM_Plex_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/components/auth-provider";
import { TokenExpiryGuard } from "@/components/token-expiry-guard";
import { ThemeInjector } from "@/components/theme-injector";
import { PublicEnvScript } from "@/components/public-env-script";
import Script from "next/script";
import { ToastProvider } from "@/components/ui/toast";
import "./globals.css";

// Primary font: Inter - Used by OpenAI, clean and highly readable
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  fallback: ["system-ui", "arial"],
});

// Alternative: Source Sans 3 - Adobe's open source, excellent readability
const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
  display: "swap",
  fallback: ["system-ui", "arial"],
});

// Alternative: IBM Plex Sans - Professional, used by IBM/Carbon
const ibmPlex = IBM_Plex_Sans({
  variable: "--font-ibm-plex",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  fallback: ["system-ui", "arial"],
});

// Monospace: JetBrains Mono - Best for code, like VSCode
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
  fallback: ["monospace", "Courier New"],
});

// Branding defaults
const DEFAULT_TAGLINE = "Multi-Agent Collaboration & Workflow Automation";
const DEFAULT_DESCRIPTION = "AI agents and native apps collaborating across tools and teams to get work done.";
const DEFAULT_APP_NAME = "CAIPE";

// Get branding from environment variables
const tagline = process.env.NEXT_PUBLIC_TAGLINE || DEFAULT_TAGLINE;
const description = process.env.NEXT_PUBLIC_DESCRIPTION || DEFAULT_DESCRIPTION;
const appName = process.env.NEXT_PUBLIC_APP_NAME || DEFAULT_APP_NAME;
const fullDescription = `${tagline} - ${description}`;

export const metadata: Metadata = {
  title: `${appName} UI`,
  description: fullDescription,
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon.ico", sizes: "any" },
    ],
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
  openGraph: {
    title: `${appName} UI`,
    description: fullDescription,
    url: "https://caipe.example.com",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Layer 1: Static file generated by entrypoint.sh at container start.
            Loads synchronously before any React code -- guaranteed to have
            runtime NEXT_PUBLIC_* env vars in Docker/K8s deployments. */}
        <Script src="/env-config.js" strategy="beforeInteractive" />
        {/* Layer 2: Server Component that reads process.env at request time.
            Merges with Layer 1 values (won't overwrite with empties). */}
        <PublicEnvScript />
      </head>
      <body
        className={`${inter.variable} ${sourceSans.variable} ${ibmPlex.variable} ${jetbrainsMono.variable} font-sans antialiased`}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="data-theme"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange={false}
            themes={["light", "dark", "midnight", "nord", "tokyo"]}
          >
            <ToastProvider>
              <ThemeInjector />
              <TokenExpiryGuard />
              {children}
            </ToastProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
