apiVersion: v2
# pyproject.toml version
appVersion: 0.1.11 # Do NOT bump this unless actually bumping pyproject.toml version
name: ai-platform-engineering
description: Parent chart to deploy multiple agent subcharts as different platform agents
sources:
- https://github.com/cnoe-io/ai-platform-engineering/charts
# Chart version for ai-platform-engineering parent chart
version: 0.4.0
dependencies:
  # AI Platform Engineer Multi-Agent
  - name: supervisor-agent
    # Chart version for agent subchart
    version: 0.2.0
  # Single agent chart used multiple times with different aliases
  - name: agent
    version: 0.3.0
    alias: agent-argocd
    tags:
      - agent-argocd
      - basic
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.argocd
  - name: agent
    version: 0.3.0
    alias: agent-aws
    tags:
      - agent-aws
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.aws
  - name: agent
    version: 0.3.0
    alias: agent-backstage
    tags:
      - agent-backstage
      - basic
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.backstage
  - name: agent
    version: 0.3.0
    alias: agent-confluence
    tags:
      - agent-confluence
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.confluence
  - name: agent
    version: 0.3.0
    alias: agent-github
    tags:
      - agent-github
      - basic
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.github
  - name: agent
    version: 0.3.0
    alias: agent-jira
    tags:
      - agent-jira
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.jira
  - name: agent
    version: 0.3.0
    alias: agent-komodor
    tags:
      - agent-komodor
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.komodor
  - name: agent
    version: 0.3.0
    alias: agent-pagerduty
    tags:
      - agent-pagerduty
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.pagerduty
  - name: agent
    version: 0.3.0
    alias: agent-slack
    tags:
      - agent-slack
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.slack
  - name: agent
    version: 0.3.0
    alias: agent-splunk
    tags:
      - agent-splunk
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.splunk
  - name: agent
    version: 0.3.0
    alias: agent-webex
    tags:
      - agent-webex
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.webex
    # AGNTCY Slim dataplane service
  - name: slim
    version: v0.1.8
    repository: oci://ghcr.io/agntcy/slim/helm
    condition: global.slim.enabled # NOTE: slim uses condition, not tags as it requires global variables to be passed into other subcharts
  - name: slim-control-plane
    version: v0.1.3
    repository: oci://ghcr.io/agntcy/slim/helm
    condition: global.slim.enabled
  - name: rag-stack
    version: 0.0.2
    repository: file://../rag-stack # TODO: might be changed to be separate
    tags:
      - rag-stack
      - complete
    import-values:
      - child: agentExports.data
        parent: global.enabledSubAgents.rag
  # Backstage plugin agent forge
  - name: backstage-plugin-agent-forge
    version: 0.1.0
    tags:
      - backstage-agent-forge
