apiVersion: v2
# pyproject.toml version
appVersion: 0.1.5
name: ai-platform-engineering
description: Parent chart to deploy multiple agent subcharts as different platform agents
sources:
- https://github.com/cnoe-io/ai-platform-engineering/charts
# Chart version for ai-platform-engineering parent chart
version: 0.2.0
dependencies:
  # AI Platform Engineer Multi-Agent
  - name: supervisor-agent
    # Chart version for agent subchart
    version: 0.1.0
    condition: supervisor-agent.enabled
  # Backstage plugin agent forge
  - name: backstage-plugin-agent-forge
    version: 0.1.0
    condition: backstage-plugin-agent-forge.enabled
  # Single agent chart used multiple times with different aliases
  - name: agent
    version: 0.2.0
    alias: agent-argocd
    condition: global.enabledSubAgents.argocd
  - name: agent
    version: 0.2.0
    alias: agent-backstage
    condition: global.enabledSubAgents.backstage
  - name: agent
    version: 0.2.0
    alias: agent-confluence
    condition: global.enabledSubAgents.confluence
  - name: agent
    version: 0.2.0
    alias: agent-github
    condition: global.enabledSubAgents.github
  - name: agent
    version: 0.2.0
    alias: agent-jira
    condition: global.enabledSubAgents.jira
  - name: agent
    version: 0.2.0
    alias: agent-pagerduty
    condition: global.enabledSubAgents.pagerduty
  - name: agent
    version: 0.2.0
    alias: agent-slack
    condition: global.enabledSubAgents.slack
  # AGNTCY Slim dataplane service
  - name: slim
    version: v0.1.8
    repository: oci://ghcr.io/agntcy/slim/helm
    condition: global.slim.enabled
  - name: slim-control-plane
    version: v0.1.3
    repository: oci://ghcr.io/agntcy/slim/helm
    condition: global.slim.enabled
  # GraphRAG services
  - name: graphrag
    version: 0.1.1
    condition: graphrag.enabled
  - name: neo4j
    version: "2025.07.1"
    repository: "https://helm.neo4j.com/neo4j"
    condition: graphrag.enabled
  # KB-RAG Stack - Complete stack including web, server, agent, Redis, and Milvus
  - name: milvus
    version: "5.0.2"
    repository: "https://zilliztech.github.io/milvus-helm/"
    condition: kb-rag-stack.enabled
  - name: kb-rag-stack
    version: 0.1.0
    condition: kb-rag-stack.enabled
