apiVersion: v2
# pyproject.toml version
appVersion: 0.1.11 # Do NOT bump this unless actually bumping pyproject.toml version
name: ai-platform-engineering
description: Parent chart to deploy multiple agent subcharts as different platform agents
sources:
- https://github.com/cnoe-io/ai-platform-engineering/charts
# Chart version for ai-platform-engineering parent chart
version: 0.2.4
dependencies:
  # AI Platform Engineer Multi-Agent
  - name: supervisor-agent
    # Chart version for agent subchart
    version: 0.1.0
  # Backstage plugin agent forge
  - name: backstage-plugin-agent-forge
    version: 0.1.0
    tags:
      - backstage-agent-forge
  # Single agent chart used multiple times with different aliases
  - name: agent
    version: 0.2.0
    alias: agent-argocd
    tags:
      - agent-argocd
      - basic
      - complete
  - name: agent
    version: 0.2.0
    alias: agent-aws
    tags:
      - agent-aws
      - complete
  - name: agent
    version: 0.2.0
    alias: agent-backstage
    tags:
      - agent-backstage
      - basic
      - complete
  - name: agent
    version: 0.2.0
    alias: agent-confluence
    tags:
      - agent-confluence
      - complete
  - name: agent
    version: 0.2.0
    alias: agent-github
    tags:
      - agent-github
      - basic
      - complete
  - name: agent
    version: 0.2.0
    alias: agent-jira
    tags:
      - agent-jira
      - complete
  - name: agent
    version: 0.2.0
    alias: agent-komodor
    tags:
      - agent-komodor
      - complete
  - name: agent
    version: 0.2.0
    alias: agent-pagerduty
    tags:
      - agent-pagerduty
      - complete
  - name: agent
    version: 0.2.0
    alias: agent-slack
    tags:
      - agent-slack
      - complete
  - name: agent
    version: 0.2.0
    alias: agent-splunk
    tags:
      - agent-splunk
      - complete
  - name: agent
    version: 0.2.0
    alias: agent-webex
    tags:
      - agent-webex
      - complete
    # AGNTCY Slim dataplane service
  - name: slim
    version: v0.1.8
    repository: oci://ghcr.io/agntcy/slim/helm
    condition: global.slim.enabled # NOTE: slim uses condition, not tags as it requires global variables to be passed into other subcharts
  - name: slim-control-plane
    version: v0.1.3
    repository: oci://ghcr.io/agntcy/slim/helm
    condition: global.slim.enabled
  # GraphRAG services
  - name: graphrag
    version: 0.1.1
    tags:
      - graphrag
      - complete
  - name: neo4j
    version: "2025.07.1"
    repository: "https://helm.neo4j.com/neo4j"
    tags:
      - graphrag
      - complete
  # KB-RAG Stack - Complete stack including web, server, agent, Redis, and Milvus
  - name: kb-rag-stack
    version: 0.1.4
    tags:
      - kb-rag-stack
      - complete
  - name: milvus
    version: "5.0.2"
    repository: "https://zilliztech.github.io/milvus-helm/"
    tags:
      - kb-rag-stack
      - complete
