tags:
  complete: true

# Global configuration shared across all subcharts
global:
  slim:
    enabled: true

  llmSecrets:
    create: false # do not create llm secret in subcharts (use global or existing llm secret)
    secretName: "existing-llm-secret"

######### Supervisor agent configuration #########
supervisor-agent:
  image:
    repository: "ghcr.io/cnoe-io/ai-platform-engineering"
    tag: "latest"
    pullPolicy: "Always"
    args: ["platform-engineer"]

######### Sub-agent configurations #########
# Agent configurations using aliases from Chart.yaml
agent-argocd:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-argocd"
    tag: "a2a_stream_common_code-44"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/mcp-argocd"
      tag: "a2a_stream_common_code-44"
  agentSecrets:
    secretName: "argocd-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-backstage:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-backstage"
    tag: "a2a_stream_common_code-44"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/mcp-backstage"
      tag: "a2a_stream_common_code-44"
  agentSecrets:
    secretName: "backstage-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-confluence:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-confluence"
    tag: "a2a_stream_common_code-44"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/mcp-confluence"
      tag: "a2a_stream_common_code-44"
  agentSecrets:
    secretName: "agent-confluence-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-github:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-github"
    tag: "a2a_stream_common_code-44"
  mcp:
    useRemoteMcpServer: true
  agentSecrets:
    secretName: "github-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-jira:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-jira"
    tag: "a2a_stream_common_code-44"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/mcp-jira"
      tag: "a2a_stream_common_code-44"
  agentSecrets:
    secretName: "atlassian-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-pagerduty:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-pagerduty"
    tag: "a2a_stream_common_code-44"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/mcp-pagerduty"
      tag: "a2a_stream_common_code-44"
  agentSecrets:
    secretName: "pagerduty-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-slack:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-slack"
    tag: "a2a_stream_common_code-44"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/mcp-slack"
      tag: "a2a_stream_common_code-44"
  agentSecrets:
    secretName: "slack-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-aws:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-aws"
    tag: "a2a_stream_common_code-44"
  mcp:
    mode: "stdio"
  agentSecrets:
    secretName: "aws-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml
  mcp:
    mode: "stdio"

agent-splunk:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-splunk"
    tag: "a2a_stream_common_code-44"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/mcp-splunk"
      tag: "a2a_stream_common_code-44"
  agentSecrets:
    secretName: "splunk-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-webex:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-webex"
    tag: "a2a_stream_common_code-44"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/mcp-webex"
      tag: "a2a_stream_common_code-44"
  agentSecrets:
    secretName: "webex-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-komodor:
  image:
    repository: "ghcr.io/cnoe-io/prebuild/agent-komodor"
    tag: "a2a_stream_common_code-44"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/mcp-komodor"
      tag: "a2a_stream_common_code-44"
  agentSecrets:
    secretName: "komodor-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

kb-rag-stack:
  rag-server:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/caipe-rag-server"
      tag: "a2a_stream_common_code-44"
  agent-rag:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/caipe-rag-agent-rag"
      tag: "a2a_stream_common_code-44"
  agent-ontology:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/caipe-rag-agent-ontology"
      tag: "a2a_stream_common_code-44"
  rag-webui:
    image:
      repository: "ghcr.io/cnoe-io/prebuild/caipe-rag-webui"
      tag: "a2a_stream_common_code-44"
