# Global agent configuration (applied to all agents)
global:
  externalSecrets:
    enabled: false
  ingress:
    enabled: false

# Agent configurations using aliases from Chart.yaml
agent-argocd:
  enabled: true
  nameOverride: "agent-argocd"
  image:
    repository: "ghcr.io/cnoe-io/agent-argocd"

agent-pagerduty:
  enabled: true
  nameOverride: "agent-pagerduty"
  image:
    repository: "ghcr.io/cnoe-io/agent-pagerduty"

agent-github:
  enabled: true
  nameOverride: "agent-github"
  image:
    repository: "ghcr.io/cnoe-io/agent-github"

agent-atlassian:
  enabled: true
  nameOverride: "agent-atlassian"
  image:
    repository: "ghcr.io/cnoe-io/agent-jira"

agent-backstage:
  enabled: true
  nameOverride: "agent-backstage"
  image:
    repository: "ghcr.io/cnoe-io/agent-backstage"

agent-slack:
  enabled: true
  nameOverride: "agent-slack"
  image:
    repository: "ghcr.io/cnoe-io/agent-slack"
