# AI Platform Engineer Multi-Agent
ai-platform-engineering:
  enabled: true
  nameOverride: "ai-platform-engineering"
  isMultiAgent: true
  image:
    repository: "ghcr.io/cnoe-io/ai-platform-engineering"
    tag: "stable"
    command: ["poetry", "run", "ai-platform-engineering"]
    args: ["platform-engineer"]
  multiAgentConfig:
    protocol: "a2a"
    port: "8000"
    releasePrefix: "ai-platform-engineering"
    agents:
      - argocd
      - atlassian
      - pagerduty
      - github
      - slack
      - komodor

# Backstage plugin agent forge
backstage-plugin-agent-forge:
  enabled: true
  nameOverride: "backstage-plugin-agent-forge"
  image:
    repository: "ghcr.io/cnoe-io/backstage-plugin-agent-forge"
    tag: "latest"
  isMultiAgent: true
  service:
    port: "3000"

# Agent configurations using aliases from Chart.yaml
agent-argocd:
  enabled: false
  nameOverride: "agent-argocd"
  image:
    repository: "ghcr.io/cnoe-io/agent-argocd"

agent-pagerduty:
  enabled: false
  nameOverride: "agent-pagerduty"
  image:
    repository: "ghcr.io/cnoe-io/agent-pagerduty"

agent-github:
  enabled: false
  nameOverride: "agent-github"
  image:
    repository: "ghcr.io/cnoe-io/agent-github"

agent-atlassian:
  enabled: true
  nameOverride: "agent-atlassian"
  image:
    repository: "ghcr.io/cnoe-io/agent-atlassian"

agent-backstage:
  enabled: true
  nameOverride: "agent-backstage"
  image:
    repository: "ghcr.io/cnoe-io/agent-backstage"

agent-slack:
  enabled: false
  nameOverride: "agent-slack"
  image:
    repository: "ghcr.io/cnoe-io/agent-slack"

agent-confluence:
  enabled: false
  nameOverride: "agent-confluence"
  image:
    repository: "ghcr.io/cnoe-io/agent-confluence"

agent-jira:
  enabled: false
  nameOverride: "agent-jira"
  image:
    repository: "ghcr.io/cnoe-io/agent-jira"

agent-reflection:
  enabled: false
  nameOverride: "agent-reflection"
  image:
    repository: "ghcr.io/cnoe-io/agent-reflection"
