# Global configuration shared across all subcharts
global:
  enabledSubAgents:
    argocd: false
    backstage: false
    confluence: false
    github: false
    jira: false
    pagerduty: false
    slack: false
  createLlmSecret: false # if true, llm secret will be created by the parent chart. Otherwise, expect existing llm secret
  llmSecrets:
    create: false # do not create llm secret in subcharts (use global or existing llm secret)
    secretName: "llm-secret"
  externalSecrets:
    enabled: false
  slim:
    enabled: true
    endpoint: "http://ai-platform-engineering-slim:46357"
    transport: "slim"

# AI Platform Engineer Multi-Agent
supervisor-agent:
  nameOverride: "supervisor-agent"
  image:
    repository: "ghcr.io/cnoe-io/ai-platform-engineering"
    tag: "stable"
    pullPolicy: "Always"
    args: ["platform-engineer"]
  env:
    EXTERNAL_URL: "http://localhost:8000"  # Agent url for the client
  multiAgentConfig:
    protocol: "a2a"
    port: "8000"

# Agent configurations using aliases from Chart.yaml
agent-argocd:
  nameOverride: "agent-argocd"
  image:
    repository: "ghcr.io/cnoe-io/agent-argocd"
    pullPolicy: "Always"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/mcp-argocd"
      tag: "stable"
      pullPolicy: "Always"
    mode: "http" # Options: stdio, http
    port: 8000

agent-backstage:
  nameOverride: "agent-backstage"
  image:
    repository: "ghcr.io/cnoe-io/agent-backstage"
    pullPolicy: "Always"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/mcp-backstage"
      tag: "stable"
      pullPolicy: "Always"
    mode: "http" # Options: stdio, http
    port: 8000

agent-confluence:
  nameOverride: "agent-confluence"
  image:
    repository: "ghcr.io/cnoe-io/agent-confluence"
    pullPolicy: "Always"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/mcp-confluence"
      tag: "stable"
      pullPolicy: "Always"
    mode: "http" # Options: stdio, http
    port: 8000

agent-github:
  nameOverride: "agent-github"
  image:
    repository: "ghcr.io/cnoe-io/agent-github"
    pullPolicy: "Always"
  mcp:
    useRemoteMcpServer: true

agent-jira:
  nameOverride: "agent-jira"
  image:
    repository: "ghcr.io/cnoe-io/agent-jira"
    pullPolicy: "Always"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/mcp-jira"
      tag: "stable"
      pullPolicy: "Always"
    mode: "http" # Options: stdio, http
    port: 8000

agent-pagerduty:
  nameOverride: "agent-pagerduty"
  image:
    repository: "ghcr.io/cnoe-io/agent-pagerduty"
    pullPolicy: "Always"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/mcp-pagerduty"
      tag: "stable"
      pullPolicy: "Always"
    mode: "http" # Options: stdio, http
    port: 8000

agent-slack:
  nameOverride: "agent-slack"
  image:
    repository: "ghcr.io/cnoe-io/agent-slack"
    pullPolicy: "Always"
  mcp:
    image:
      repository: "ghcr.io/cnoe-io/mcp-slack"
      tag: "stable"
      pullPolicy: "Always"
    mode: "http" # Options: stdio, http
    port: 8000
    pullPolicy: "Always"

# Backstage plugin agent forge
backstage-plugin-agent-forge:
  enabled: true
  nameOverride: "backstage-plugin-agent-forge"
  image:
    repository: "ghcr.io/cnoe-io/backstage-plugin-agent-forge"
    tag: "latest"
    pullPolicy: "Always"
  service:
    ports:
      - name: http
        port: 3000
        protocol: TCP
      - name: backend
        port: 7007
        protocol: TCP

graphrag:
  enabled: true
  neo4jNameOverride: "graphrag-neo4j" # This needs to match the value in neo4j.fullnameOverride

# neo4j is used by graphrag to store the graph data. If graphrag.enabled is false, neo4j is not deployed.
neo4j:
  fullnameOverride: "graphrag-neo4j"
  config:
    server.directories.plugins: "/var/lib/neo4j/labs"
    dbms.security.procedures.unrestricted: "apoc.*"
    dbms.security.procedures.allowlist: "apoc.*"
    server.config.strict_validation.enabled: "false"
  apoc_config:
    apoc.trigger.enabled: "true"
    apoc.import.file.enabled: "true"
  disableLookups: true
  services:
    neo4j:
      enabled: false
  neo4j:
    name: graphrag-neo4j
    password: "dummy_password" # This dummy password needs to match the value in graphrag.neo4j.auth.password
    resources:
      cpu: "1"
      memory: "2Gi"

  volumes:
    data:
      mode: "dynamic"
      dynamic:
        storageClassName: gp2

# KB-RAG Stack - Complete stack including web, server, agent, Redis, and Milvus
kb-rag-stack:
  enabled: false

  # KB-RAG Web configuration
  kb-rag-web:
    enabled: true
    image:
      repository: "ghcr.io/cnoe-io/kb-rag-web"
      tag: "latest"
      pullPolicy: "Always"

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: false
      className: ""
      annotations: {}
      hosts:
        - host: kb-rag-web.local
          paths:
            - path: /
              pathType: Prefix
      tls: []

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # KB-RAG Server configuration
  kb-rag-server:
    enabled: true
    image:
      repository: "ghcr.io/cnoe-io/kb-rag-server"
      tag: "latest"
      pullPolicy: "Always"

    service:
      type: ClusterIP
      port: 9446

    env:
      REDIS_URL: "redis://kb-rag-redis:6379/0"
      MILVUS_HOST: "milvus-standalone"
      MILVUS_PORT: "19530"

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Agent configuration (standard agent chart)
  kb-rag-agent:
    enabled: true
    nameOverride: "kb-rag-agent"
    image:
      repository: "ghcr.io/cnoe-io/kb-rag-agent-a2a"
      tag: "latest"
      pullPolicy: "Always"

    service:
      type: ClusterIP
      port: 8000

    env:
      MILVUS_HOST: "milvus-standalone"
      MILVUS_PORT: "19530"

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 2Gi

  # KB-RAG Redis configuration
  kb-rag-redis:
    enabled: true
    image:
      repository: "redis"
      tag: "7.2-alpine"
      pullPolicy: "Always"

    service:
      type: ClusterIP
      port: 6379

    persistence:
      enabled: true
      size: 1Gi
      storageClass: ""

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Redis configuration
    redis:
      maxmemory: "256mb"
      maxmemoryPolicy: "allkeys-lru"
      save: "60 1"
      appendonly: "yes"

# Optimize Milvus configuration for minimal memory usage
milvus:
  # Use standalone mode with RocksDB instead of Pulsar
  cluster:
    enabled: false

  standalone:
    replicas: 1
    messageQueue: rocksmq  # Use RocksDB instead of Pulsar (saves ~12GB memory)
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
    persistence:
      enabled: true
      size: 50Gi  # Reduced from default 500Gi
      storageClass: ""
      accessMode: ReadWriteOnce

  # Disable cluster components when using standalone
  proxy:
    enabled: false
  rootCoordinator:
    enabled: false
  queryCoordinator:
    enabled: false
  queryNode:
    enabled: false
  indexCoordinator:
    enabled: false
  indexNode:
    enabled: false
  dataCoordinator:
    enabled: false
  dataNode:
    enabled: false
  mixCoordinator:
    enabled: false

  # Optimize MinIO for minimal memory usage
  minio:
    enabled: true
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    persistence:
      enabled: true
      size: 50Gi  # Match requested storage size
      storageClass: ""
      accessMode: ReadWriteOnce

  # Disable Pulsar to save memory
  pulsar:
    enabled: false

  # Disable Pulsar v3 to save memory
  pulsarv3:
    enabled: false

  # Disable Kafka
  kafka:
    enabled: false

  # Minimal etcd configuration
  etcd:
    enabled: true
    replicaCount: 1
    service:
      ports:
        client:
          port: 2379
          protocol: TCP
        peer:
          port: 2380
          protocol: TCP
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
    persistence:
      enabled: true
      size: 10Gi
