# AI Platform Engineer Multi-Agent
ai-platform-engineering:
  enabled: true
  nameOverride: "ai-platform-engineering"
  isMultiAgent: true
  image:
    repository: "ghcr.io/cnoe-io/ai-platform-engineering"
    tag: "stable"
    command: ["poetry", "run", "ai-platform-engineering"]
    args: ["platform-engineer"]
  multiAgentConfig:
    protocol: "a2a"
    port: "8000"
    releasePrefix: "ai-platform-engineering"
    agents:
      - argocd
      - backstage
      - confluence
      - github
      - jira
      - pagerduty
      - slack
# Backstage plugin agent forge
backstage-plugin-agent-forge:
  enabled: true
  nameOverride: "backstage-plugin-agent-forge"
  image:
    repository: "ghcr.io/cnoe-io/backstage-plugin-agent-forge"
    tag: "latest"
  isBackstagePlugin: true
  service:
    ports:
      - name: frontend
        port: 3000
        protocol: TCP
      - name: backend
        port: 7007
        protocol: TCP

# Agent configurations using aliases from Chart.yaml
agent-argocd:
  enabled: false
  nameOverride: "agent-argocd"
  image:
    repository: "ghcr.io/cnoe-io/agent-argocd"

agent-backstage:
  enabled: false
  nameOverride: "agent-backstage"
  image:
    repository: "ghcr.io/cnoe-io/agent-backstage"

agent-confluence:
  enabled: false
  nameOverride: "agent-confluence"
  image:
    repository: "ghcr.io/cnoe-io/agent-confluence"

agent-github:
  enabled: false
  nameOverride: "agent-github"
  image:
    repository: "ghcr.io/cnoe-io/agent-github"

agent-jira:
  enabled: false
  nameOverride: "agent-jira"
  image:
    repository: "ghcr.io/cnoe-io/agent-jira"

agent-pagerduty:
  enabled: false
  nameOverride: "agent-pagerduty"
  image:
    repository: "ghcr.io/cnoe-io/agent-pagerduty"

agent-slack:
  enabled: false
  nameOverride: "agent-slack"
  image:
    repository: "ghcr.io/cnoe-io/agent-slack"
