name: Docker Build and Push

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  IMAGE_NAME: cnoe-io/ai-platform-engineering

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.filter.outputs.core }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            core:
              - 'build/**'
              - 'ai_platform_engineering/multi_agents/**'
              - 'ai_platform_engineering/utils/**'
              - 'ai_platform_engineering/common/**'
              - 'ai_platform_engineering/knowledge_bases/**'
              - 'pyproject.toml'
              - 'uv.lock'
              - 'ai_platform_engineering/__init__.py'

  build-and-push:
    runs-on: ubuntu-latest
    needs: determine-changes
    if: needs.determine-changes.outputs.should_build == 'true' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write

    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch,prefix=
            type=ref,event=tag,prefix=
            type=sha,format=short,prefix=

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and Push A2A Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max