name: Nexigraph (GraphRAG/Gen) Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'ai_platform_engineering/knowledge_bases/graph_rag/**'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - 'ai_platform_engineering/knowledge_bases/graph_rag/**'
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        component: [agent_graph_gen, agent_graph_qa, server, clients]
      fail-fast: false

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: cnoe-io/nexigraph-${{ matrix.component }}
      BUILD_CTX: ai_platform_engineering/knowledge_bases/graph_rag/nexigraph/nexigraph
      DOCKERFILE: ai_platform_engineering/knowledge_bases/graph_rag/nexigraph/nexigraph/${{ matrix.component }}/Dockerfile

    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BUILD_CTX }}
          file: ${{ env.DOCKERFILE }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max