name: Pre-Release Supervisor Agent Docker Build and Push

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'build/**'
      - 'ai_platform_engineering/multi_agents/**'
      - 'ai_platform_engineering/utils/**'
      - 'ai_platform_engineering/common/**'
      - 'ai_platform_engineering/knowledge_bases/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'ai_platform_engineering/__init__.py'

env:
  IMAGE_NAME: cnoe-io/prebuild/ai-platform-engineering

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' &&
      startsWith(github.head_ref, 'prebuild/') &&
      github.event.action != 'closed'
    outputs:
      should_build: ${{ steps.filter.outputs.core }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            core:
              - 'build/**'
              - 'ai_platform_engineering/multi_agents/**'
              - 'ai_platform_engineering/utils/**'
              - 'ai_platform_engineering/common/**'
              - 'ai_platform_engineering/knowledge_bases/**'
              - 'pyproject.toml'
              - 'uv.lock'
              - 'ai_platform_engineering/__init__.py'

  build-and-push:
    runs-on: ubuntu-latest
    needs: determine-changes
    if: |
      needs.determine-changes.outputs.should_build == 'true' &&
      startsWith(github.head_ref, 'prebuild/') &&
      github.event.action != 'closed'
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute prebuild tag
        id: compute_tag
        shell: bash
        run: |
          BRANCH="${{ github.head_ref || github.ref_name }}"
          BRANCH_NO_PREFIX="${BRANCH#prebuild/}"
          BRANCH_SANITIZED="${BRANCH_NO_PREFIX//\//-}"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          COMMIT_COUNT=$(git rev-list --count origin/${{ github.event.pull_request.base.ref }}..HEAD)
          echo "BRANCH_BARE=${BRANCH_SANITIZED}" >> $GITHUB_ENV
          echo "PREBUILD_TAG=${BRANCH_SANITIZED}-${COMMIT_COUNT}" >> $GITHUB_ENV

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.PREBUILD_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and Push A2A Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 💬 Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        env:
          IMAGE_REPO: ghcr.io/${{ env.IMAGE_NAME }}
          IMAGE_REF: ghcr.io/${{ env.IMAGE_NAME }}:${{ env.PREBUILD_TAG }}
          PREBUILD_TAG: ${{ env.PREBUILD_TAG }}
        with:
          script: |
            const body = `## 🐳 Prebuild Docker Image Published

            **Repository:** \`${process.env.IMAGE_REPO}\`
            **Tag:** \`${process.env.PREBUILD_TAG}\`

            ### Usage
            \`\`\`bash
            docker pull ${process.env.IMAGE_REF}
            \`\`\`

            > **Note:** This prebuild image will be automatically cleaned up when the PR is closed or merged.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

  cleanup-images:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && startsWith(github.event.pull_request.head.ref, 'prebuild/')
    permissions:
      contents: read
      packages: write
    env:
      OWNER: ${{ github.repository_owner }}
      PACKAGE_NAME: prebuild/ai-platform-engineering
    steps:
      - name: Delete prebuild images for branch
        uses: actions/github-script@v7
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        with:
          script: |
            const owner = process.env.OWNER;
            const rawBranch = process.env.HEAD_REF || '';
            const branchNoPrefix = rawBranch.startsWith('prebuild/') ? rawBranch.substring('prebuild/'.length) : rawBranch;
            const sanitized = branchNoPrefix.replace(/\//g, '-');
            const prefix = `${sanitized}-`;
            const packageName = process.env.PACKAGE_NAME;
            const packageType = 'container';
            try {
              const versions = await github.paginate(github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg, {
                org: owner,
                package_type: packageType,
                package_name: packageName,
                per_page: 100,
              });
              const toDelete = versions.filter(v => (v.metadata?.container?.tags || []).some(t => t.startsWith(prefix)));
              for (const v of toDelete) {
                await github.rest.packages.deletePackageVersionForOrg({
                  org: owner,
                  package_type: packageType,
                  package_name: packageName,
                  package_version_id: v.id,
                });
              }
              core.info(`Deleted ${toDelete.length} versions for ${packageName} with tag prefix ${prefix}`);
            } catch (e) {
              if (e.status === 404) {
                core.info(`Package ${packageName} not found in org ${owner}, skipping.`);
              } else {
                throw e;
              }
            }