---
name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

          /home/ubuntu/.local/bin/uv venv

          @echo "Installing ai_platform_engineering, agents, and argocd..."

          @. .venv/bin/activate && uv add pytest-asyncio --group unittest
          @. .venv/bin/activate && uv add ai_platform_engineering/agents/argocd --dev
          @. .venv/bin/activate && uv add ai_platform_engineering/agents/komodor --dev

          @echo "Running tests..."
          @. .venv/bin/activate && uv run pytest --ignore=integration
