replicaCount: 1

image:
  repository: ghcr.io/cnoe-io/agent-pagerduty
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

env:
  - name: PAGERDUTY_API_KEY
    value: ""
  - name: PAGERDUTY_API_URL
    value: ""

nodeSelector: {}
tolerations: []
affinity: {} 